// -------------------------------------------------------------
//
// Module: Lowpass_1_MHz_V3
// Generated by MATLAB(R) 9.14 and Filter Design HDL Coder 3.1.13.
// Generated on: 2023-06-13 12:07:24
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: F:\Heavy_Software\Quartus_Prime_13.1\quartus\proyek
// EDAScriptGeneration: off
// Name: Lowpass_1_MHz_V3
// TargetLanguage: Verilog
// TestBenchName: Hlp_tb
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate      : 50 MHz
// Response         : Lowpass
// Specification    : N,Fc,Ap,Ast
// Stopband Atten.  : 60 dB
// Passband Ripple  : 1 dB
// Filter Order     : 100
// Cutoff Frequency : 1.5 MHz
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 101
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s8,11 -> [-6.250000e-02 6.250000e-02)
// Input             : s14,0 -> [-8192 8192)
// Filter Internals  : Full Precision
//   Output          : s26,11 -> [-16384 16384)  (auto determined)
//   Product         : s21,11 -> [-512 512)  (auto determined)
//   Accumulator     : s26,11 -> [-16384 16384)  (auto determined)
//   Round Mode      : No rounding
//   Overflow Mode   : No overflow
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module Lowpass_1_MHz_V3
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [13:0] filter_in; //sfix14
  output  signed [25:0] filter_out; //sfix26_En11

////////////////////////////////////////////////////////////////
//Module Architecture: Lowpass_1_MHz_V3
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [7:0] coeff1 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff2 = 8'b00000001; //sfix8_En11
  parameter signed [7:0] coeff3 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff4 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff5 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff6 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff7 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff8 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff9 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff10 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff11 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff12 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff13 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff14 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff15 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff16 = 8'b00000000; //sfix8_En11
  parameter signed [7:0] coeff17 = 8'b11111111; //sfix8_En11
  parameter signed [7:0] coeff18 = 8'b11111101; //sfix8_En11
  parameter signed [7:0] coeff19 = 8'b11111011; //sfix8_En11
  parameter signed [7:0] coeff20 = 8'b11111000; //sfix8_En11
  parameter signed [7:0] coeff21 = 8'b11110110; //sfix8_En11
  parameter signed [7:0] coeff22 = 8'b11110011; //sfix8_En11
  parameter signed [7:0] coeff23 = 8'b11110001; //sfix8_En11
  parameter signed [7:0] coeff24 = 8'b11101111; //sfix8_En11
  parameter signed [7:0] coeff25 = 8'b11101101; //sfix8_En11
  parameter signed [7:0] coeff26 = 8'b11101011; //sfix8_En11
  parameter signed [7:0] coeff27 = 8'b11101010; //sfix8_En11
  parameter signed [7:0] coeff28 = 8'b11101010; //sfix8_En11
  parameter signed [7:0] coeff29 = 8'b11101010; //sfix8_En11
  parameter signed [7:0] coeff30 = 8'b11101100; //sfix8_En11
  parameter signed [7:0] coeff31 = 8'b11101110; //sfix8_En11
  parameter signed [7:0] coeff32 = 8'b11110001; //sfix8_En11
  parameter signed [7:0] coeff33 = 8'b11110110; //sfix8_En11
  parameter signed [7:0] coeff34 = 8'b11111011; //sfix8_En11
  parameter signed [7:0] coeff35 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff36 = 8'b00001001; //sfix8_En11
  parameter signed [7:0] coeff37 = 8'b00010010; //sfix8_En11
  parameter signed [7:0] coeff38 = 8'b00011011; //sfix8_En11
  parameter signed [7:0] coeff39 = 8'b00100101; //sfix8_En11
  parameter signed [7:0] coeff40 = 8'b00101111; //sfix8_En11
  parameter signed [7:0] coeff41 = 8'b00111010; //sfix8_En11
  parameter signed [7:0] coeff42 = 8'b01000100; //sfix8_En11
  parameter signed [7:0] coeff43 = 8'b01001110; //sfix8_En11
  parameter signed [7:0] coeff44 = 8'b01011000; //sfix8_En11
  parameter signed [7:0] coeff45 = 8'b01100001; //sfix8_En11
  parameter signed [7:0] coeff46 = 8'b01101001; //sfix8_En11
  parameter signed [7:0] coeff47 = 8'b01101111; //sfix8_En11
  parameter signed [7:0] coeff48 = 8'b01110101; //sfix8_En11
  parameter signed [7:0] coeff49 = 8'b01111001; //sfix8_En11
  parameter signed [7:0] coeff50 = 8'b01111011; //sfix8_En11
  parameter signed [7:0] coeff51 = 8'b01111100; //sfix8_En11
  parameter signed [7:0] coeff52 = 8'b01111011; //sfix8_En11
  parameter signed [7:0] coeff53 = 8'b01111001; //sfix8_En11
  parameter signed [7:0] coeff54 = 8'b01110101; //sfix8_En11
  parameter signed [7:0] coeff55 = 8'b01101111; //sfix8_En11
  parameter signed [7:0] coeff56 = 8'b01101001; //sfix8_En11
  parameter signed [7:0] coeff57 = 8'b01100001; //sfix8_En11
  parameter signed [7:0] coeff58 = 8'b01011000; //sfix8_En11
  parameter signed [7:0] coeff59 = 8'b01001110; //sfix8_En11
  parameter signed [7:0] coeff60 = 8'b01000100; //sfix8_En11
  parameter signed [7:0] coeff61 = 8'b00111010; //sfix8_En11
  parameter signed [7:0] coeff62 = 8'b00101111; //sfix8_En11
  parameter signed [7:0] coeff63 = 8'b00100101; //sfix8_En11
  parameter signed [7:0] coeff64 = 8'b00011011; //sfix8_En11
  parameter signed [7:0] coeff65 = 8'b00010010; //sfix8_En11
  parameter signed [7:0] coeff66 = 8'b00001001; //sfix8_En11
  parameter signed [7:0] coeff67 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff68 = 8'b11111011; //sfix8_En11
  parameter signed [7:0] coeff69 = 8'b11110110; //sfix8_En11
  parameter signed [7:0] coeff70 = 8'b11110001; //sfix8_En11
  parameter signed [7:0] coeff71 = 8'b11101110; //sfix8_En11
  parameter signed [7:0] coeff72 = 8'b11101100; //sfix8_En11
  parameter signed [7:0] coeff73 = 8'b11101010; //sfix8_En11
  parameter signed [7:0] coeff74 = 8'b11101010; //sfix8_En11
  parameter signed [7:0] coeff75 = 8'b11101010; //sfix8_En11
  parameter signed [7:0] coeff76 = 8'b11101011; //sfix8_En11
  parameter signed [7:0] coeff77 = 8'b11101101; //sfix8_En11
  parameter signed [7:0] coeff78 = 8'b11101111; //sfix8_En11
  parameter signed [7:0] coeff79 = 8'b11110001; //sfix8_En11
  parameter signed [7:0] coeff80 = 8'b11110011; //sfix8_En11
  parameter signed [7:0] coeff81 = 8'b11110110; //sfix8_En11
  parameter signed [7:0] coeff82 = 8'b11111000; //sfix8_En11
  parameter signed [7:0] coeff83 = 8'b11111011; //sfix8_En11
  parameter signed [7:0] coeff84 = 8'b11111101; //sfix8_En11
  parameter signed [7:0] coeff85 = 8'b11111111; //sfix8_En11
  parameter signed [7:0] coeff86 = 8'b00000000; //sfix8_En11
  parameter signed [7:0] coeff87 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff88 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff89 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff90 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff91 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff92 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff93 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff94 = 8'b00000100; //sfix8_En11
  parameter signed [7:0] coeff95 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff96 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff97 = 8'b00000011; //sfix8_En11
  parameter signed [7:0] coeff98 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff99 = 8'b00000010; //sfix8_En11
  parameter signed [7:0] coeff100 = 8'b00000001; //sfix8_En11
  parameter signed [7:0] coeff101 = 8'b00000010; //sfix8_En11

  // Signals
  reg  signed [13:0] delay_pipeline [0:100] ; // sfix14
  wire signed [20:0] product101; // sfix21_En11
  wire signed [20:0] product100; // sfix21_En11
  wire signed [20:0] product99; // sfix21_En11
  wire signed [20:0] product98; // sfix21_En11
  wire signed [20:0] product97; // sfix21_En11
  wire signed [21:0] mul_temp; // sfix22_En11
  wire signed [20:0] product96; // sfix21_En11
  wire signed [21:0] mul_temp_1; // sfix22_En11
  wire signed [20:0] product95; // sfix21_En11
  wire signed [21:0] mul_temp_2; // sfix22_En11
  wire signed [20:0] product94; // sfix21_En11
  wire signed [20:0] product93; // sfix21_En11
  wire signed [20:0] product92; // sfix21_En11
  wire signed [20:0] product91; // sfix21_En11
  wire signed [20:0] product90; // sfix21_En11
  wire signed [20:0] product89; // sfix21_En11
  wire signed [20:0] product88; // sfix21_En11
  wire signed [21:0] mul_temp_3; // sfix22_En11
  wire signed [20:0] product87; // sfix21_En11
  wire signed [20:0] product85; // sfix21_En11
  wire signed [14:0] mulpwr2_temp; // sfix15
  wire signed [20:0] product84; // sfix21_En11
  wire signed [21:0] mul_temp_4; // sfix22_En11
  wire signed [20:0] product83; // sfix21_En11
  wire signed [21:0] mul_temp_5; // sfix22_En11
  wire signed [20:0] product82; // sfix21_En11
  wire signed [14:0] mulpwr2_temp_1; // sfix15
  wire signed [20:0] product81; // sfix21_En11
  wire signed [21:0] mul_temp_6; // sfix22_En11
  wire signed [20:0] product80; // sfix21_En11
  wire signed [21:0] mul_temp_7; // sfix22_En11
  wire signed [20:0] product79; // sfix21_En11
  wire signed [21:0] mul_temp_8; // sfix22_En11
  wire signed [20:0] product78; // sfix21_En11
  wire signed [21:0] mul_temp_9; // sfix22_En11
  wire signed [20:0] product77; // sfix21_En11
  wire signed [21:0] mul_temp_10; // sfix22_En11
  wire signed [20:0] product76; // sfix21_En11
  wire signed [21:0] mul_temp_11; // sfix22_En11
  wire signed [20:0] product75; // sfix21_En11
  wire signed [21:0] mul_temp_12; // sfix22_En11
  wire signed [20:0] product74; // sfix21_En11
  wire signed [21:0] mul_temp_13; // sfix22_En11
  wire signed [20:0] product73; // sfix21_En11
  wire signed [21:0] mul_temp_14; // sfix22_En11
  wire signed [20:0] product72; // sfix21_En11
  wire signed [21:0] mul_temp_15; // sfix22_En11
  wire signed [20:0] product71; // sfix21_En11
  wire signed [21:0] mul_temp_16; // sfix22_En11
  wire signed [20:0] product70; // sfix21_En11
  wire signed [21:0] mul_temp_17; // sfix22_En11
  wire signed [20:0] product69; // sfix21_En11
  wire signed [21:0] mul_temp_18; // sfix22_En11
  wire signed [20:0] product68; // sfix21_En11
  wire signed [21:0] mul_temp_19; // sfix22_En11
  wire signed [20:0] product67; // sfix21_En11
  wire signed [20:0] product66; // sfix21_En11
  wire signed [21:0] mul_temp_20; // sfix22_En11
  wire signed [20:0] product65; // sfix21_En11
  wire signed [21:0] mul_temp_21; // sfix22_En11
  wire signed [20:0] product64; // sfix21_En11
  wire signed [21:0] mul_temp_22; // sfix22_En11
  wire signed [20:0] product63; // sfix21_En11
  wire signed [21:0] mul_temp_23; // sfix22_En11
  wire signed [20:0] product62; // sfix21_En11
  wire signed [21:0] mul_temp_24; // sfix22_En11
  wire signed [20:0] product61; // sfix21_En11
  wire signed [21:0] mul_temp_25; // sfix22_En11
  wire signed [20:0] product60; // sfix21_En11
  wire signed [21:0] mul_temp_26; // sfix22_En11
  wire signed [20:0] product59; // sfix21_En11
  wire signed [21:0] mul_temp_27; // sfix22_En11
  wire signed [20:0] product58; // sfix21_En11
  wire signed [21:0] mul_temp_28; // sfix22_En11
  wire signed [20:0] product57; // sfix21_En11
  wire signed [21:0] mul_temp_29; // sfix22_En11
  wire signed [20:0] product56; // sfix21_En11
  wire signed [21:0] mul_temp_30; // sfix22_En11
  wire signed [20:0] product55; // sfix21_En11
  wire signed [21:0] mul_temp_31; // sfix22_En11
  wire signed [20:0] product54; // sfix21_En11
  wire signed [21:0] mul_temp_32; // sfix22_En11
  wire signed [20:0] product53; // sfix21_En11
  wire signed [21:0] mul_temp_33; // sfix22_En11
  wire signed [20:0] product52; // sfix21_En11
  wire signed [21:0] mul_temp_34; // sfix22_En11
  wire signed [20:0] product51; // sfix21_En11
  wire signed [21:0] mul_temp_35; // sfix22_En11
  wire signed [20:0] product50; // sfix21_En11
  wire signed [21:0] mul_temp_36; // sfix22_En11
  wire signed [20:0] product49; // sfix21_En11
  wire signed [21:0] mul_temp_37; // sfix22_En11
  wire signed [20:0] product48; // sfix21_En11
  wire signed [21:0] mul_temp_38; // sfix22_En11
  wire signed [20:0] product47; // sfix21_En11
  wire signed [21:0] mul_temp_39; // sfix22_En11
  wire signed [20:0] product46; // sfix21_En11
  wire signed [21:0] mul_temp_40; // sfix22_En11
  wire signed [20:0] product45; // sfix21_En11
  wire signed [21:0] mul_temp_41; // sfix22_En11
  wire signed [20:0] product44; // sfix21_En11
  wire signed [21:0] mul_temp_42; // sfix22_En11
  wire signed [20:0] product43; // sfix21_En11
  wire signed [21:0] mul_temp_43; // sfix22_En11
  wire signed [20:0] product42; // sfix21_En11
  wire signed [21:0] mul_temp_44; // sfix22_En11
  wire signed [20:0] product41; // sfix21_En11
  wire signed [21:0] mul_temp_45; // sfix22_En11
  wire signed [20:0] product40; // sfix21_En11
  wire signed [21:0] mul_temp_46; // sfix22_En11
  wire signed [20:0] product39; // sfix21_En11
  wire signed [21:0] mul_temp_47; // sfix22_En11
  wire signed [20:0] product38; // sfix21_En11
  wire signed [21:0] mul_temp_48; // sfix22_En11
  wire signed [20:0] product37; // sfix21_En11
  wire signed [21:0] mul_temp_49; // sfix22_En11
  wire signed [20:0] product36; // sfix21_En11
  wire signed [21:0] mul_temp_50; // sfix22_En11
  wire signed [20:0] product35; // sfix21_En11
  wire signed [20:0] product34; // sfix21_En11
  wire signed [21:0] mul_temp_51; // sfix22_En11
  wire signed [20:0] product33; // sfix21_En11
  wire signed [21:0] mul_temp_52; // sfix22_En11
  wire signed [20:0] product32; // sfix21_En11
  wire signed [21:0] mul_temp_53; // sfix22_En11
  wire signed [20:0] product31; // sfix21_En11
  wire signed [21:0] mul_temp_54; // sfix22_En11
  wire signed [20:0] product30; // sfix21_En11
  wire signed [21:0] mul_temp_55; // sfix22_En11
  wire signed [20:0] product29; // sfix21_En11
  wire signed [21:0] mul_temp_56; // sfix22_En11
  wire signed [20:0] product28; // sfix21_En11
  wire signed [21:0] mul_temp_57; // sfix22_En11
  wire signed [20:0] product27; // sfix21_En11
  wire signed [21:0] mul_temp_58; // sfix22_En11
  wire signed [20:0] product26; // sfix21_En11
  wire signed [21:0] mul_temp_59; // sfix22_En11
  wire signed [20:0] product25; // sfix21_En11
  wire signed [21:0] mul_temp_60; // sfix22_En11
  wire signed [20:0] product24; // sfix21_En11
  wire signed [21:0] mul_temp_61; // sfix22_En11
  wire signed [20:0] product23; // sfix21_En11
  wire signed [21:0] mul_temp_62; // sfix22_En11
  wire signed [20:0] product22; // sfix21_En11
  wire signed [21:0] mul_temp_63; // sfix22_En11
  wire signed [20:0] product21; // sfix21_En11
  wire signed [21:0] mul_temp_64; // sfix22_En11
  wire signed [20:0] product20; // sfix21_En11
  wire signed [14:0] mulpwr2_temp_2; // sfix15
  wire signed [20:0] product19; // sfix21_En11
  wire signed [21:0] mul_temp_65; // sfix22_En11
  wire signed [20:0] product18; // sfix21_En11
  wire signed [21:0] mul_temp_66; // sfix22_En11
  wire signed [20:0] product17; // sfix21_En11
  wire signed [14:0] mulpwr2_temp_3; // sfix15
  wire signed [20:0] product15; // sfix21_En11
  wire signed [20:0] product14; // sfix21_En11
  wire signed [21:0] mul_temp_67; // sfix22_En11
  wire signed [20:0] product13; // sfix21_En11
  wire signed [20:0] product12; // sfix21_En11
  wire signed [20:0] product11; // sfix21_En11
  wire signed [20:0] product10; // sfix21_En11
  wire signed [20:0] product9; // sfix21_En11
  wire signed [20:0] product8; // sfix21_En11
  wire signed [20:0] product7; // sfix21_En11
  wire signed [21:0] mul_temp_68; // sfix22_En11
  wire signed [20:0] product6; // sfix21_En11
  wire signed [21:0] mul_temp_69; // sfix22_En11
  wire signed [20:0] product5; // sfix21_En11
  wire signed [21:0] mul_temp_70; // sfix22_En11
  wire signed [20:0] product4; // sfix21_En11
  wire signed [20:0] product3; // sfix21_En11
  wire signed [20:0] product2; // sfix21_En11
  wire signed [25:0] product1_cast; // sfix26_En11
  wire signed [20:0] product1; // sfix21_En11
  wire signed [25:0] sum1; // sfix26_En11
  wire signed [25:0] add_signext; // sfix26_En11
  wire signed [25:0] add_signext_1; // sfix26_En11
  wire signed [26:0] add_temp; // sfix27_En11
  wire signed [25:0] sum2; // sfix26_En11
  wire signed [25:0] add_signext_2; // sfix26_En11
  wire signed [25:0] add_signext_3; // sfix26_En11
  wire signed [26:0] add_temp_1; // sfix27_En11
  wire signed [25:0] sum3; // sfix26_En11
  wire signed [25:0] add_signext_4; // sfix26_En11
  wire signed [25:0] add_signext_5; // sfix26_En11
  wire signed [26:0] add_temp_2; // sfix27_En11
  wire signed [25:0] sum4; // sfix26_En11
  wire signed [25:0] add_signext_6; // sfix26_En11
  wire signed [25:0] add_signext_7; // sfix26_En11
  wire signed [26:0] add_temp_3; // sfix27_En11
  wire signed [25:0] sum5; // sfix26_En11
  wire signed [25:0] add_signext_8; // sfix26_En11
  wire signed [25:0] add_signext_9; // sfix26_En11
  wire signed [26:0] add_temp_4; // sfix27_En11
  wire signed [25:0] sum6; // sfix26_En11
  wire signed [25:0] add_signext_10; // sfix26_En11
  wire signed [25:0] add_signext_11; // sfix26_En11
  wire signed [26:0] add_temp_5; // sfix27_En11
  wire signed [25:0] sum7; // sfix26_En11
  wire signed [25:0] add_signext_12; // sfix26_En11
  wire signed [25:0] add_signext_13; // sfix26_En11
  wire signed [26:0] add_temp_6; // sfix27_En11
  wire signed [25:0] sum8; // sfix26_En11
  wire signed [25:0] add_signext_14; // sfix26_En11
  wire signed [25:0] add_signext_15; // sfix26_En11
  wire signed [26:0] add_temp_7; // sfix27_En11
  wire signed [25:0] sum9; // sfix26_En11
  wire signed [25:0] add_signext_16; // sfix26_En11
  wire signed [25:0] add_signext_17; // sfix26_En11
  wire signed [26:0] add_temp_8; // sfix27_En11
  wire signed [25:0] sum10; // sfix26_En11
  wire signed [25:0] add_signext_18; // sfix26_En11
  wire signed [25:0] add_signext_19; // sfix26_En11
  wire signed [26:0] add_temp_9; // sfix27_En11
  wire signed [25:0] sum11; // sfix26_En11
  wire signed [25:0] add_signext_20; // sfix26_En11
  wire signed [25:0] add_signext_21; // sfix26_En11
  wire signed [26:0] add_temp_10; // sfix27_En11
  wire signed [25:0] sum12; // sfix26_En11
  wire signed [25:0] add_signext_22; // sfix26_En11
  wire signed [25:0] add_signext_23; // sfix26_En11
  wire signed [26:0] add_temp_11; // sfix27_En11
  wire signed [25:0] sum13; // sfix26_En11
  wire signed [25:0] add_signext_24; // sfix26_En11
  wire signed [25:0] add_signext_25; // sfix26_En11
  wire signed [26:0] add_temp_12; // sfix27_En11
  wire signed [25:0] sum14; // sfix26_En11
  wire signed [25:0] add_signext_26; // sfix26_En11
  wire signed [25:0] add_signext_27; // sfix26_En11
  wire signed [26:0] add_temp_13; // sfix27_En11
  wire signed [25:0] sum15; // sfix26_En11
  wire signed [25:0] add_signext_28; // sfix26_En11
  wire signed [25:0] add_signext_29; // sfix26_En11
  wire signed [26:0] add_temp_14; // sfix27_En11
  wire signed [25:0] sum16; // sfix26_En11
  wire signed [25:0] add_signext_30; // sfix26_En11
  wire signed [25:0] add_signext_31; // sfix26_En11
  wire signed [26:0] add_temp_15; // sfix27_En11
  wire signed [25:0] sum17; // sfix26_En11
  wire signed [25:0] add_signext_32; // sfix26_En11
  wire signed [25:0] add_signext_33; // sfix26_En11
  wire signed [26:0] add_temp_16; // sfix27_En11
  wire signed [25:0] sum18; // sfix26_En11
  wire signed [25:0] add_signext_34; // sfix26_En11
  wire signed [25:0] add_signext_35; // sfix26_En11
  wire signed [26:0] add_temp_17; // sfix27_En11
  wire signed [25:0] sum19; // sfix26_En11
  wire signed [25:0] add_signext_36; // sfix26_En11
  wire signed [25:0] add_signext_37; // sfix26_En11
  wire signed [26:0] add_temp_18; // sfix27_En11
  wire signed [25:0] sum20; // sfix26_En11
  wire signed [25:0] add_signext_38; // sfix26_En11
  wire signed [25:0] add_signext_39; // sfix26_En11
  wire signed [26:0] add_temp_19; // sfix27_En11
  wire signed [25:0] sum21; // sfix26_En11
  wire signed [25:0] add_signext_40; // sfix26_En11
  wire signed [25:0] add_signext_41; // sfix26_En11
  wire signed [26:0] add_temp_20; // sfix27_En11
  wire signed [25:0] sum22; // sfix26_En11
  wire signed [25:0] add_signext_42; // sfix26_En11
  wire signed [25:0] add_signext_43; // sfix26_En11
  wire signed [26:0] add_temp_21; // sfix27_En11
  wire signed [25:0] sum23; // sfix26_En11
  wire signed [25:0] add_signext_44; // sfix26_En11
  wire signed [25:0] add_signext_45; // sfix26_En11
  wire signed [26:0] add_temp_22; // sfix27_En11
  wire signed [25:0] sum24; // sfix26_En11
  wire signed [25:0] add_signext_46; // sfix26_En11
  wire signed [25:0] add_signext_47; // sfix26_En11
  wire signed [26:0] add_temp_23; // sfix27_En11
  wire signed [25:0] sum25; // sfix26_En11
  wire signed [25:0] add_signext_48; // sfix26_En11
  wire signed [25:0] add_signext_49; // sfix26_En11
  wire signed [26:0] add_temp_24; // sfix27_En11
  wire signed [25:0] sum26; // sfix26_En11
  wire signed [25:0] add_signext_50; // sfix26_En11
  wire signed [25:0] add_signext_51; // sfix26_En11
  wire signed [26:0] add_temp_25; // sfix27_En11
  wire signed [25:0] sum27; // sfix26_En11
  wire signed [25:0] add_signext_52; // sfix26_En11
  wire signed [25:0] add_signext_53; // sfix26_En11
  wire signed [26:0] add_temp_26; // sfix27_En11
  wire signed [25:0] sum28; // sfix26_En11
  wire signed [25:0] add_signext_54; // sfix26_En11
  wire signed [25:0] add_signext_55; // sfix26_En11
  wire signed [26:0] add_temp_27; // sfix27_En11
  wire signed [25:0] sum29; // sfix26_En11
  wire signed [25:0] add_signext_56; // sfix26_En11
  wire signed [25:0] add_signext_57; // sfix26_En11
  wire signed [26:0] add_temp_28; // sfix27_En11
  wire signed [25:0] sum30; // sfix26_En11
  wire signed [25:0] add_signext_58; // sfix26_En11
  wire signed [25:0] add_signext_59; // sfix26_En11
  wire signed [26:0] add_temp_29; // sfix27_En11
  wire signed [25:0] sum31; // sfix26_En11
  wire signed [25:0] add_signext_60; // sfix26_En11
  wire signed [25:0] add_signext_61; // sfix26_En11
  wire signed [26:0] add_temp_30; // sfix27_En11
  wire signed [25:0] sum32; // sfix26_En11
  wire signed [25:0] add_signext_62; // sfix26_En11
  wire signed [25:0] add_signext_63; // sfix26_En11
  wire signed [26:0] add_temp_31; // sfix27_En11
  wire signed [25:0] sum33; // sfix26_En11
  wire signed [25:0] add_signext_64; // sfix26_En11
  wire signed [25:0] add_signext_65; // sfix26_En11
  wire signed [26:0] add_temp_32; // sfix27_En11
  wire signed [25:0] sum34; // sfix26_En11
  wire signed [25:0] add_signext_66; // sfix26_En11
  wire signed [25:0] add_signext_67; // sfix26_En11
  wire signed [26:0] add_temp_33; // sfix27_En11
  wire signed [25:0] sum35; // sfix26_En11
  wire signed [25:0] add_signext_68; // sfix26_En11
  wire signed [25:0] add_signext_69; // sfix26_En11
  wire signed [26:0] add_temp_34; // sfix27_En11
  wire signed [25:0] sum36; // sfix26_En11
  wire signed [25:0] add_signext_70; // sfix26_En11
  wire signed [25:0] add_signext_71; // sfix26_En11
  wire signed [26:0] add_temp_35; // sfix27_En11
  wire signed [25:0] sum37; // sfix26_En11
  wire signed [25:0] add_signext_72; // sfix26_En11
  wire signed [25:0] add_signext_73; // sfix26_En11
  wire signed [26:0] add_temp_36; // sfix27_En11
  wire signed [25:0] sum38; // sfix26_En11
  wire signed [25:0] add_signext_74; // sfix26_En11
  wire signed [25:0] add_signext_75; // sfix26_En11
  wire signed [26:0] add_temp_37; // sfix27_En11
  wire signed [25:0] sum39; // sfix26_En11
  wire signed [25:0] add_signext_76; // sfix26_En11
  wire signed [25:0] add_signext_77; // sfix26_En11
  wire signed [26:0] add_temp_38; // sfix27_En11
  wire signed [25:0] sum40; // sfix26_En11
  wire signed [25:0] add_signext_78; // sfix26_En11
  wire signed [25:0] add_signext_79; // sfix26_En11
  wire signed [26:0] add_temp_39; // sfix27_En11
  wire signed [25:0] sum41; // sfix26_En11
  wire signed [25:0] add_signext_80; // sfix26_En11
  wire signed [25:0] add_signext_81; // sfix26_En11
  wire signed [26:0] add_temp_40; // sfix27_En11
  wire signed [25:0] sum42; // sfix26_En11
  wire signed [25:0] add_signext_82; // sfix26_En11
  wire signed [25:0] add_signext_83; // sfix26_En11
  wire signed [26:0] add_temp_41; // sfix27_En11
  wire signed [25:0] sum43; // sfix26_En11
  wire signed [25:0] add_signext_84; // sfix26_En11
  wire signed [25:0] add_signext_85; // sfix26_En11
  wire signed [26:0] add_temp_42; // sfix27_En11
  wire signed [25:0] sum44; // sfix26_En11
  wire signed [25:0] add_signext_86; // sfix26_En11
  wire signed [25:0] add_signext_87; // sfix26_En11
  wire signed [26:0] add_temp_43; // sfix27_En11
  wire signed [25:0] sum45; // sfix26_En11
  wire signed [25:0] add_signext_88; // sfix26_En11
  wire signed [25:0] add_signext_89; // sfix26_En11
  wire signed [26:0] add_temp_44; // sfix27_En11
  wire signed [25:0] sum46; // sfix26_En11
  wire signed [25:0] add_signext_90; // sfix26_En11
  wire signed [25:0] add_signext_91; // sfix26_En11
  wire signed [26:0] add_temp_45; // sfix27_En11
  wire signed [25:0] sum47; // sfix26_En11
  wire signed [25:0] add_signext_92; // sfix26_En11
  wire signed [25:0] add_signext_93; // sfix26_En11
  wire signed [26:0] add_temp_46; // sfix27_En11
  wire signed [25:0] sum48; // sfix26_En11
  wire signed [25:0] add_signext_94; // sfix26_En11
  wire signed [25:0] add_signext_95; // sfix26_En11
  wire signed [26:0] add_temp_47; // sfix27_En11
  wire signed [25:0] sum49; // sfix26_En11
  wire signed [25:0] add_signext_96; // sfix26_En11
  wire signed [25:0] add_signext_97; // sfix26_En11
  wire signed [26:0] add_temp_48; // sfix27_En11
  wire signed [25:0] sum50; // sfix26_En11
  wire signed [25:0] add_signext_98; // sfix26_En11
  wire signed [25:0] add_signext_99; // sfix26_En11
  wire signed [26:0] add_temp_49; // sfix27_En11
  wire signed [25:0] sum51; // sfix26_En11
  wire signed [25:0] add_signext_100; // sfix26_En11
  wire signed [25:0] add_signext_101; // sfix26_En11
  wire signed [26:0] add_temp_50; // sfix27_En11
  wire signed [25:0] sum52; // sfix26_En11
  wire signed [25:0] add_signext_102; // sfix26_En11
  wire signed [25:0] add_signext_103; // sfix26_En11
  wire signed [26:0] add_temp_51; // sfix27_En11
  wire signed [25:0] sum53; // sfix26_En11
  wire signed [25:0] add_signext_104; // sfix26_En11
  wire signed [25:0] add_signext_105; // sfix26_En11
  wire signed [26:0] add_temp_52; // sfix27_En11
  wire signed [25:0] sum54; // sfix26_En11
  wire signed [25:0] add_signext_106; // sfix26_En11
  wire signed [25:0] add_signext_107; // sfix26_En11
  wire signed [26:0] add_temp_53; // sfix27_En11
  wire signed [25:0] sum55; // sfix26_En11
  wire signed [25:0] add_signext_108; // sfix26_En11
  wire signed [25:0] add_signext_109; // sfix26_En11
  wire signed [26:0] add_temp_54; // sfix27_En11
  wire signed [25:0] sum56; // sfix26_En11
  wire signed [25:0] add_signext_110; // sfix26_En11
  wire signed [25:0] add_signext_111; // sfix26_En11
  wire signed [26:0] add_temp_55; // sfix27_En11
  wire signed [25:0] sum57; // sfix26_En11
  wire signed [25:0] add_signext_112; // sfix26_En11
  wire signed [25:0] add_signext_113; // sfix26_En11
  wire signed [26:0] add_temp_56; // sfix27_En11
  wire signed [25:0] sum58; // sfix26_En11
  wire signed [25:0] add_signext_114; // sfix26_En11
  wire signed [25:0] add_signext_115; // sfix26_En11
  wire signed [26:0] add_temp_57; // sfix27_En11
  wire signed [25:0] sum59; // sfix26_En11
  wire signed [25:0] add_signext_116; // sfix26_En11
  wire signed [25:0] add_signext_117; // sfix26_En11
  wire signed [26:0] add_temp_58; // sfix27_En11
  wire signed [25:0] sum60; // sfix26_En11
  wire signed [25:0] add_signext_118; // sfix26_En11
  wire signed [25:0] add_signext_119; // sfix26_En11
  wire signed [26:0] add_temp_59; // sfix27_En11
  wire signed [25:0] sum61; // sfix26_En11
  wire signed [25:0] add_signext_120; // sfix26_En11
  wire signed [25:0] add_signext_121; // sfix26_En11
  wire signed [26:0] add_temp_60; // sfix27_En11
  wire signed [25:0] sum62; // sfix26_En11
  wire signed [25:0] add_signext_122; // sfix26_En11
  wire signed [25:0] add_signext_123; // sfix26_En11
  wire signed [26:0] add_temp_61; // sfix27_En11
  wire signed [25:0] sum63; // sfix26_En11
  wire signed [25:0] add_signext_124; // sfix26_En11
  wire signed [25:0] add_signext_125; // sfix26_En11
  wire signed [26:0] add_temp_62; // sfix27_En11
  wire signed [25:0] sum64; // sfix26_En11
  wire signed [25:0] add_signext_126; // sfix26_En11
  wire signed [25:0] add_signext_127; // sfix26_En11
  wire signed [26:0] add_temp_63; // sfix27_En11
  wire signed [25:0] sum65; // sfix26_En11
  wire signed [25:0] add_signext_128; // sfix26_En11
  wire signed [25:0] add_signext_129; // sfix26_En11
  wire signed [26:0] add_temp_64; // sfix27_En11
  wire signed [25:0] sum66; // sfix26_En11
  wire signed [25:0] add_signext_130; // sfix26_En11
  wire signed [25:0] add_signext_131; // sfix26_En11
  wire signed [26:0] add_temp_65; // sfix27_En11
  wire signed [25:0] sum67; // sfix26_En11
  wire signed [25:0] add_signext_132; // sfix26_En11
  wire signed [25:0] add_signext_133; // sfix26_En11
  wire signed [26:0] add_temp_66; // sfix27_En11
  wire signed [25:0] sum68; // sfix26_En11
  wire signed [25:0] add_signext_134; // sfix26_En11
  wire signed [25:0] add_signext_135; // sfix26_En11
  wire signed [26:0] add_temp_67; // sfix27_En11
  wire signed [25:0] sum69; // sfix26_En11
  wire signed [25:0] add_signext_136; // sfix26_En11
  wire signed [25:0] add_signext_137; // sfix26_En11
  wire signed [26:0] add_temp_68; // sfix27_En11
  wire signed [25:0] sum70; // sfix26_En11
  wire signed [25:0] add_signext_138; // sfix26_En11
  wire signed [25:0] add_signext_139; // sfix26_En11
  wire signed [26:0] add_temp_69; // sfix27_En11
  wire signed [25:0] sum71; // sfix26_En11
  wire signed [25:0] add_signext_140; // sfix26_En11
  wire signed [25:0] add_signext_141; // sfix26_En11
  wire signed [26:0] add_temp_70; // sfix27_En11
  wire signed [25:0] sum72; // sfix26_En11
  wire signed [25:0] add_signext_142; // sfix26_En11
  wire signed [25:0] add_signext_143; // sfix26_En11
  wire signed [26:0] add_temp_71; // sfix27_En11
  wire signed [25:0] sum73; // sfix26_En11
  wire signed [25:0] add_signext_144; // sfix26_En11
  wire signed [25:0] add_signext_145; // sfix26_En11
  wire signed [26:0] add_temp_72; // sfix27_En11
  wire signed [25:0] sum74; // sfix26_En11
  wire signed [25:0] add_signext_146; // sfix26_En11
  wire signed [25:0] add_signext_147; // sfix26_En11
  wire signed [26:0] add_temp_73; // sfix27_En11
  wire signed [25:0] sum75; // sfix26_En11
  wire signed [25:0] add_signext_148; // sfix26_En11
  wire signed [25:0] add_signext_149; // sfix26_En11
  wire signed [26:0] add_temp_74; // sfix27_En11
  wire signed [25:0] sum76; // sfix26_En11
  wire signed [25:0] add_signext_150; // sfix26_En11
  wire signed [25:0] add_signext_151; // sfix26_En11
  wire signed [26:0] add_temp_75; // sfix27_En11
  wire signed [25:0] sum77; // sfix26_En11
  wire signed [25:0] add_signext_152; // sfix26_En11
  wire signed [25:0] add_signext_153; // sfix26_En11
  wire signed [26:0] add_temp_76; // sfix27_En11
  wire signed [25:0] sum78; // sfix26_En11
  wire signed [25:0] add_signext_154; // sfix26_En11
  wire signed [25:0] add_signext_155; // sfix26_En11
  wire signed [26:0] add_temp_77; // sfix27_En11
  wire signed [25:0] sum79; // sfix26_En11
  wire signed [25:0] add_signext_156; // sfix26_En11
  wire signed [25:0] add_signext_157; // sfix26_En11
  wire signed [26:0] add_temp_78; // sfix27_En11
  wire signed [25:0] sum80; // sfix26_En11
  wire signed [25:0] add_signext_158; // sfix26_En11
  wire signed [25:0] add_signext_159; // sfix26_En11
  wire signed [26:0] add_temp_79; // sfix27_En11
  wire signed [25:0] sum81; // sfix26_En11
  wire signed [25:0] add_signext_160; // sfix26_En11
  wire signed [25:0] add_signext_161; // sfix26_En11
  wire signed [26:0] add_temp_80; // sfix27_En11
  wire signed [25:0] sum82; // sfix26_En11
  wire signed [25:0] add_signext_162; // sfix26_En11
  wire signed [25:0] add_signext_163; // sfix26_En11
  wire signed [26:0] add_temp_81; // sfix27_En11
  wire signed [25:0] sum83; // sfix26_En11
  wire signed [25:0] add_signext_164; // sfix26_En11
  wire signed [25:0] add_signext_165; // sfix26_En11
  wire signed [26:0] add_temp_82; // sfix27_En11
  wire signed [25:0] sum84; // sfix26_En11
  wire signed [25:0] add_signext_166; // sfix26_En11
  wire signed [25:0] add_signext_167; // sfix26_En11
  wire signed [26:0] add_temp_83; // sfix27_En11
  wire signed [25:0] sum85; // sfix26_En11
  wire signed [25:0] add_signext_168; // sfix26_En11
  wire signed [25:0] add_signext_169; // sfix26_En11
  wire signed [26:0] add_temp_84; // sfix27_En11
  wire signed [25:0] sum86; // sfix26_En11
  wire signed [25:0] add_signext_170; // sfix26_En11
  wire signed [25:0] add_signext_171; // sfix26_En11
  wire signed [26:0] add_temp_85; // sfix27_En11
  wire signed [25:0] sum87; // sfix26_En11
  wire signed [25:0] add_signext_172; // sfix26_En11
  wire signed [25:0] add_signext_173; // sfix26_En11
  wire signed [26:0] add_temp_86; // sfix27_En11
  wire signed [25:0] sum88; // sfix26_En11
  wire signed [25:0] add_signext_174; // sfix26_En11
  wire signed [25:0] add_signext_175; // sfix26_En11
  wire signed [26:0] add_temp_87; // sfix27_En11
  wire signed [25:0] sum89; // sfix26_En11
  wire signed [25:0] add_signext_176; // sfix26_En11
  wire signed [25:0] add_signext_177; // sfix26_En11
  wire signed [26:0] add_temp_88; // sfix27_En11
  wire signed [25:0] sum90; // sfix26_En11
  wire signed [25:0] add_signext_178; // sfix26_En11
  wire signed [25:0] add_signext_179; // sfix26_En11
  wire signed [26:0] add_temp_89; // sfix27_En11
  wire signed [25:0] sum91; // sfix26_En11
  wire signed [25:0] add_signext_180; // sfix26_En11
  wire signed [25:0] add_signext_181; // sfix26_En11
  wire signed [26:0] add_temp_90; // sfix27_En11
  wire signed [25:0] sum92; // sfix26_En11
  wire signed [25:0] add_signext_182; // sfix26_En11
  wire signed [25:0] add_signext_183; // sfix26_En11
  wire signed [26:0] add_temp_91; // sfix27_En11
  wire signed [25:0] sum93; // sfix26_En11
  wire signed [25:0] add_signext_184; // sfix26_En11
  wire signed [25:0] add_signext_185; // sfix26_En11
  wire signed [26:0] add_temp_92; // sfix27_En11
  wire signed [25:0] sum94; // sfix26_En11
  wire signed [25:0] add_signext_186; // sfix26_En11
  wire signed [25:0] add_signext_187; // sfix26_En11
  wire signed [26:0] add_temp_93; // sfix27_En11
  wire signed [25:0] sum95; // sfix26_En11
  wire signed [25:0] add_signext_188; // sfix26_En11
  wire signed [25:0] add_signext_189; // sfix26_En11
  wire signed [26:0] add_temp_94; // sfix27_En11
  wire signed [25:0] sum96; // sfix26_En11
  wire signed [25:0] add_signext_190; // sfix26_En11
  wire signed [25:0] add_signext_191; // sfix26_En11
  wire signed [26:0] add_temp_95; // sfix27_En11
  wire signed [25:0] sum97; // sfix26_En11
  wire signed [25:0] add_signext_192; // sfix26_En11
  wire signed [25:0] add_signext_193; // sfix26_En11
  wire signed [26:0] add_temp_96; // sfix27_En11
  wire signed [25:0] sum98; // sfix26_En11
  wire signed [25:0] add_signext_194; // sfix26_En11
  wire signed [25:0] add_signext_195; // sfix26_En11
  wire signed [26:0] add_temp_97; // sfix27_En11
  reg  signed [25:0] output_register; // sfix26_En11

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
        delay_pipeline[52] <= 0;
        delay_pipeline[53] <= 0;
        delay_pipeline[54] <= 0;
        delay_pipeline[55] <= 0;
        delay_pipeline[56] <= 0;
        delay_pipeline[57] <= 0;
        delay_pipeline[58] <= 0;
        delay_pipeline[59] <= 0;
        delay_pipeline[60] <= 0;
        delay_pipeline[61] <= 0;
        delay_pipeline[62] <= 0;
        delay_pipeline[63] <= 0;
        delay_pipeline[64] <= 0;
        delay_pipeline[65] <= 0;
        delay_pipeline[66] <= 0;
        delay_pipeline[67] <= 0;
        delay_pipeline[68] <= 0;
        delay_pipeline[69] <= 0;
        delay_pipeline[70] <= 0;
        delay_pipeline[71] <= 0;
        delay_pipeline[72] <= 0;
        delay_pipeline[73] <= 0;
        delay_pipeline[74] <= 0;
        delay_pipeline[75] <= 0;
        delay_pipeline[76] <= 0;
        delay_pipeline[77] <= 0;
        delay_pipeline[78] <= 0;
        delay_pipeline[79] <= 0;
        delay_pipeline[80] <= 0;
        delay_pipeline[81] <= 0;
        delay_pipeline[82] <= 0;
        delay_pipeline[83] <= 0;
        delay_pipeline[84] <= 0;
        delay_pipeline[85] <= 0;
        delay_pipeline[86] <= 0;
        delay_pipeline[87] <= 0;
        delay_pipeline[88] <= 0;
        delay_pipeline[89] <= 0;
        delay_pipeline[90] <= 0;
        delay_pipeline[91] <= 0;
        delay_pipeline[92] <= 0;
        delay_pipeline[93] <= 0;
        delay_pipeline[94] <= 0;
        delay_pipeline[95] <= 0;
        delay_pipeline[96] <= 0;
        delay_pipeline[97] <= 0;
        delay_pipeline[98] <= 0;
        delay_pipeline[99] <= 0;
        delay_pipeline[100] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
          delay_pipeline[52] <= delay_pipeline[51];
          delay_pipeline[53] <= delay_pipeline[52];
          delay_pipeline[54] <= delay_pipeline[53];
          delay_pipeline[55] <= delay_pipeline[54];
          delay_pipeline[56] <= delay_pipeline[55];
          delay_pipeline[57] <= delay_pipeline[56];
          delay_pipeline[58] <= delay_pipeline[57];
          delay_pipeline[59] <= delay_pipeline[58];
          delay_pipeline[60] <= delay_pipeline[59];
          delay_pipeline[61] <= delay_pipeline[60];
          delay_pipeline[62] <= delay_pipeline[61];
          delay_pipeline[63] <= delay_pipeline[62];
          delay_pipeline[64] <= delay_pipeline[63];
          delay_pipeline[65] <= delay_pipeline[64];
          delay_pipeline[66] <= delay_pipeline[65];
          delay_pipeline[67] <= delay_pipeline[66];
          delay_pipeline[68] <= delay_pipeline[67];
          delay_pipeline[69] <= delay_pipeline[68];
          delay_pipeline[70] <= delay_pipeline[69];
          delay_pipeline[71] <= delay_pipeline[70];
          delay_pipeline[72] <= delay_pipeline[71];
          delay_pipeline[73] <= delay_pipeline[72];
          delay_pipeline[74] <= delay_pipeline[73];
          delay_pipeline[75] <= delay_pipeline[74];
          delay_pipeline[76] <= delay_pipeline[75];
          delay_pipeline[77] <= delay_pipeline[76];
          delay_pipeline[78] <= delay_pipeline[77];
          delay_pipeline[79] <= delay_pipeline[78];
          delay_pipeline[80] <= delay_pipeline[79];
          delay_pipeline[81] <= delay_pipeline[80];
          delay_pipeline[82] <= delay_pipeline[81];
          delay_pipeline[83] <= delay_pipeline[82];
          delay_pipeline[84] <= delay_pipeline[83];
          delay_pipeline[85] <= delay_pipeline[84];
          delay_pipeline[86] <= delay_pipeline[85];
          delay_pipeline[87] <= delay_pipeline[86];
          delay_pipeline[88] <= delay_pipeline[87];
          delay_pipeline[89] <= delay_pipeline[88];
          delay_pipeline[90] <= delay_pipeline[89];
          delay_pipeline[91] <= delay_pipeline[90];
          delay_pipeline[92] <= delay_pipeline[91];
          delay_pipeline[93] <= delay_pipeline[92];
          delay_pipeline[94] <= delay_pipeline[93];
          delay_pipeline[95] <= delay_pipeline[94];
          delay_pipeline[96] <= delay_pipeline[95];
          delay_pipeline[97] <= delay_pipeline[96];
          delay_pipeline[98] <= delay_pipeline[97];
          delay_pipeline[99] <= delay_pipeline[98];
          delay_pipeline[100] <= delay_pipeline[99];
        end
      end
    end // Delay_Pipeline_process


  assign product101 = $signed({delay_pipeline[100][13:0], 1'b0});

  assign product100 = $signed({{7{delay_pipeline[99][13]}}, delay_pipeline[99]});

  assign product99 = $signed({delay_pipeline[98][13:0], 1'b0});

  assign product98 = $signed({delay_pipeline[97][13:0], 1'b0});

  assign mul_temp = delay_pipeline[96] * coeff97;
  assign product97 = mul_temp[20:0];

  assign mul_temp_1 = delay_pipeline[95] * coeff96;
  assign product96 = mul_temp_1[20:0];

  assign mul_temp_2 = delay_pipeline[94] * coeff95;
  assign product95 = mul_temp_2[20:0];

  assign product94 = $signed({delay_pipeline[93][13:0], 2'b00});

  assign product93 = $signed({delay_pipeline[92][13:0], 2'b00});

  assign product92 = $signed({delay_pipeline[91][13:0], 2'b00});

  assign product91 = $signed({delay_pipeline[90][13:0], 2'b00});

  assign product90 = $signed({delay_pipeline[89][13:0], 2'b00});

  assign product89 = $signed({delay_pipeline[88][13:0], 2'b00});

  assign mul_temp_3 = delay_pipeline[87] * coeff88;
  assign product88 = mul_temp_3[20:0];

  assign product87 = $signed({delay_pipeline[86][13:0], 1'b0});

  assign mulpwr2_temp = (delay_pipeline[84]==14'b10000000000000) ? $signed({1'b0, delay_pipeline[84]}) : -delay_pipeline[84];

  assign product85 = $signed({{6{mulpwr2_temp[14]}}, mulpwr2_temp});

  assign mul_temp_4 = delay_pipeline[83] * coeff84;
  assign product84 = mul_temp_4[20:0];

  assign mul_temp_5 = delay_pipeline[82] * coeff83;
  assign product83 = mul_temp_5[20:0];

  assign mulpwr2_temp_1 = (delay_pipeline[81]==14'b10000000000000) ? $signed({1'b0, delay_pipeline[81]}) : -delay_pipeline[81];

  assign product82 = $signed({mulpwr2_temp_1[14:0], 3'b000});

  assign mul_temp_6 = delay_pipeline[80] * coeff81;
  assign product81 = mul_temp_6[20:0];

  assign mul_temp_7 = delay_pipeline[79] * coeff80;
  assign product80 = mul_temp_7[20:0];

  assign mul_temp_8 = delay_pipeline[78] * coeff79;
  assign product79 = mul_temp_8[20:0];

  assign mul_temp_9 = delay_pipeline[77] * coeff78;
  assign product78 = mul_temp_9[20:0];

  assign mul_temp_10 = delay_pipeline[76] * coeff77;
  assign product77 = mul_temp_10[20:0];

  assign mul_temp_11 = delay_pipeline[75] * coeff76;
  assign product76 = mul_temp_11[20:0];

  assign mul_temp_12 = delay_pipeline[74] * coeff75;
  assign product75 = mul_temp_12[20:0];

  assign mul_temp_13 = delay_pipeline[73] * coeff74;
  assign product74 = mul_temp_13[20:0];

  assign mul_temp_14 = delay_pipeline[72] * coeff73;
  assign product73 = mul_temp_14[20:0];

  assign mul_temp_15 = delay_pipeline[71] * coeff72;
  assign product72 = mul_temp_15[20:0];

  assign mul_temp_16 = delay_pipeline[70] * coeff71;
  assign product71 = mul_temp_16[20:0];

  assign mul_temp_17 = delay_pipeline[69] * coeff70;
  assign product70 = mul_temp_17[20:0];

  assign mul_temp_18 = delay_pipeline[68] * coeff69;
  assign product69 = mul_temp_18[20:0];

  assign mul_temp_19 = delay_pipeline[67] * coeff68;
  assign product68 = mul_temp_19[20:0];

  assign product67 = $signed({delay_pipeline[66][13:0], 1'b0});

  assign mul_temp_20 = delay_pipeline[65] * coeff66;
  assign product66 = mul_temp_20[20:0];

  assign mul_temp_21 = delay_pipeline[64] * coeff65;
  assign product65 = mul_temp_21[20:0];

  assign mul_temp_22 = delay_pipeline[63] * coeff64;
  assign product64 = mul_temp_22[20:0];

  assign mul_temp_23 = delay_pipeline[62] * coeff63;
  assign product63 = mul_temp_23[20:0];

  assign mul_temp_24 = delay_pipeline[61] * coeff62;
  assign product62 = mul_temp_24[20:0];

  assign mul_temp_25 = delay_pipeline[60] * coeff61;
  assign product61 = mul_temp_25[20:0];

  assign mul_temp_26 = delay_pipeline[59] * coeff60;
  assign product60 = mul_temp_26[20:0];

  assign mul_temp_27 = delay_pipeline[58] * coeff59;
  assign product59 = mul_temp_27[20:0];

  assign mul_temp_28 = delay_pipeline[57] * coeff58;
  assign product58 = mul_temp_28[20:0];

  assign mul_temp_29 = delay_pipeline[56] * coeff57;
  assign product57 = mul_temp_29[20:0];

  assign mul_temp_30 = delay_pipeline[55] * coeff56;
  assign product56 = mul_temp_30[20:0];

  assign mul_temp_31 = delay_pipeline[54] * coeff55;
  assign product55 = mul_temp_31[20:0];

  assign mul_temp_32 = delay_pipeline[53] * coeff54;
  assign product54 = mul_temp_32[20:0];

  assign mul_temp_33 = delay_pipeline[52] * coeff53;
  assign product53 = mul_temp_33[20:0];

  assign mul_temp_34 = delay_pipeline[51] * coeff52;
  assign product52 = mul_temp_34[20:0];

  assign mul_temp_35 = delay_pipeline[50] * coeff51;
  assign product51 = mul_temp_35[20:0];

  assign mul_temp_36 = delay_pipeline[49] * coeff50;
  assign product50 = mul_temp_36[20:0];

  assign mul_temp_37 = delay_pipeline[48] * coeff49;
  assign product49 = mul_temp_37[20:0];

  assign mul_temp_38 = delay_pipeline[47] * coeff48;
  assign product48 = mul_temp_38[20:0];

  assign mul_temp_39 = delay_pipeline[46] * coeff47;
  assign product47 = mul_temp_39[20:0];

  assign mul_temp_40 = delay_pipeline[45] * coeff46;
  assign product46 = mul_temp_40[20:0];

  assign mul_temp_41 = delay_pipeline[44] * coeff45;
  assign product45 = mul_temp_41[20:0];

  assign mul_temp_42 = delay_pipeline[43] * coeff44;
  assign product44 = mul_temp_42[20:0];

  assign mul_temp_43 = delay_pipeline[42] * coeff43;
  assign product43 = mul_temp_43[20:0];

  assign mul_temp_44 = delay_pipeline[41] * coeff42;
  assign product42 = mul_temp_44[20:0];

  assign mul_temp_45 = delay_pipeline[40] * coeff41;
  assign product41 = mul_temp_45[20:0];

  assign mul_temp_46 = delay_pipeline[39] * coeff40;
  assign product40 = mul_temp_46[20:0];

  assign mul_temp_47 = delay_pipeline[38] * coeff39;
  assign product39 = mul_temp_47[20:0];

  assign mul_temp_48 = delay_pipeline[37] * coeff38;
  assign product38 = mul_temp_48[20:0];

  assign mul_temp_49 = delay_pipeline[36] * coeff37;
  assign product37 = mul_temp_49[20:0];

  assign mul_temp_50 = delay_pipeline[35] * coeff36;
  assign product36 = mul_temp_50[20:0];

  assign product35 = $signed({delay_pipeline[34][13:0], 1'b0});

  assign mul_temp_51 = delay_pipeline[33] * coeff34;
  assign product34 = mul_temp_51[20:0];

  assign mul_temp_52 = delay_pipeline[32] * coeff33;
  assign product33 = mul_temp_52[20:0];

  assign mul_temp_53 = delay_pipeline[31] * coeff32;
  assign product32 = mul_temp_53[20:0];

  assign mul_temp_54 = delay_pipeline[30] * coeff31;
  assign product31 = mul_temp_54[20:0];

  assign mul_temp_55 = delay_pipeline[29] * coeff30;
  assign product30 = mul_temp_55[20:0];

  assign mul_temp_56 = delay_pipeline[28] * coeff29;
  assign product29 = mul_temp_56[20:0];

  assign mul_temp_57 = delay_pipeline[27] * coeff28;
  assign product28 = mul_temp_57[20:0];

  assign mul_temp_58 = delay_pipeline[26] * coeff27;
  assign product27 = mul_temp_58[20:0];

  assign mul_temp_59 = delay_pipeline[25] * coeff26;
  assign product26 = mul_temp_59[20:0];

  assign mul_temp_60 = delay_pipeline[24] * coeff25;
  assign product25 = mul_temp_60[20:0];

  assign mul_temp_61 = delay_pipeline[23] * coeff24;
  assign product24 = mul_temp_61[20:0];

  assign mul_temp_62 = delay_pipeline[22] * coeff23;
  assign product23 = mul_temp_62[20:0];

  assign mul_temp_63 = delay_pipeline[21] * coeff22;
  assign product22 = mul_temp_63[20:0];

  assign mul_temp_64 = delay_pipeline[20] * coeff21;
  assign product21 = mul_temp_64[20:0];

  assign mulpwr2_temp_2 = (delay_pipeline[19]==14'b10000000000000) ? $signed({1'b0, delay_pipeline[19]}) : -delay_pipeline[19];

  assign product20 = $signed({mulpwr2_temp_2[14:0], 3'b000});

  assign mul_temp_65 = delay_pipeline[18] * coeff19;
  assign product19 = mul_temp_65[20:0];

  assign mul_temp_66 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_66[20:0];

  assign mulpwr2_temp_3 = (delay_pipeline[16]==14'b10000000000000) ? $signed({1'b0, delay_pipeline[16]}) : -delay_pipeline[16];

  assign product17 = $signed({{6{mulpwr2_temp_3[14]}}, mulpwr2_temp_3});

  assign product15 = $signed({delay_pipeline[14][13:0], 1'b0});

  assign mul_temp_67 = delay_pipeline[13] * coeff14;
  assign product14 = mul_temp_67[20:0];

  assign product13 = $signed({delay_pipeline[12][13:0], 2'b00});

  assign product12 = $signed({delay_pipeline[11][13:0], 2'b00});

  assign product11 = $signed({delay_pipeline[10][13:0], 2'b00});

  assign product10 = $signed({delay_pipeline[9][13:0], 2'b00});

  assign product9 = $signed({delay_pipeline[8][13:0], 2'b00});

  assign product8 = $signed({delay_pipeline[7][13:0], 2'b00});

  assign mul_temp_68 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_68[20:0];

  assign mul_temp_69 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_69[20:0];

  assign mul_temp_70 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_70[20:0];

  assign product4 = $signed({delay_pipeline[3][13:0], 1'b0});

  assign product3 = $signed({delay_pipeline[2][13:0], 1'b0});

  assign product2 = $signed({{7{delay_pipeline[1][13]}}, delay_pipeline[1]});

  assign product1_cast = $signed({{5{product1[20]}}, product1});

  assign product1 = $signed({delay_pipeline[0][13:0], 1'b0});

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{5{product2[20]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[25:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{5{product3[20]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[25:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{5{product4[20]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[25:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{5{product5[20]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[25:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{5{product6[20]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[25:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{5{product7[20]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[25:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{5{product8[20]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[25:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{5{product9[20]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[25:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{5{product10[20]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[25:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{5{product11[20]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[25:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{5{product12[20]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[25:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{5{product13[20]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[25:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{5{product14[20]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[25:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{5{product15[20]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[25:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{5{product17[20]}}, product17});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[25:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{5{product18[20]}}, product18});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[25:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{5{product19[20]}}, product19});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[25:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{5{product20[20]}}, product20});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[25:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{5{product21[20]}}, product21});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[25:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{5{product22[20]}}, product22});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[25:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{5{product23[20]}}, product23});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[25:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{5{product24[20]}}, product24});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[25:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{5{product25[20]}}, product25});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[25:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{5{product26[20]}}, product26});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[25:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{5{product27[20]}}, product27});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[25:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{5{product28[20]}}, product28});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[25:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{5{product29[20]}}, product29});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[25:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{5{product30[20]}}, product30});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[25:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{5{product31[20]}}, product31});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[25:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{5{product32[20]}}, product32});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[25:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{5{product33[20]}}, product33});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[25:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{5{product34[20]}}, product34});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[25:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = $signed({{5{product35[20]}}, product35});
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = add_temp_32[25:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = $signed({{5{product36[20]}}, product36});
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = add_temp_33[25:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = $signed({{5{product37[20]}}, product37});
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = add_temp_34[25:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = $signed({{5{product38[20]}}, product38});
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = add_temp_35[25:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = $signed({{5{product39[20]}}, product39});
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = add_temp_36[25:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = $signed({{5{product40[20]}}, product40});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = add_temp_37[25:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = $signed({{5{product41[20]}}, product41});
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = add_temp_38[25:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = $signed({{5{product42[20]}}, product42});
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = add_temp_39[25:0];

  assign add_signext_80 = sum40;
  assign add_signext_81 = $signed({{5{product43[20]}}, product43});
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum41 = add_temp_40[25:0];

  assign add_signext_82 = sum41;
  assign add_signext_83 = $signed({{5{product44[20]}}, product44});
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum42 = add_temp_41[25:0];

  assign add_signext_84 = sum42;
  assign add_signext_85 = $signed({{5{product45[20]}}, product45});
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum43 = add_temp_42[25:0];

  assign add_signext_86 = sum43;
  assign add_signext_87 = $signed({{5{product46[20]}}, product46});
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum44 = add_temp_43[25:0];

  assign add_signext_88 = sum44;
  assign add_signext_89 = $signed({{5{product47[20]}}, product47});
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum45 = add_temp_44[25:0];

  assign add_signext_90 = sum45;
  assign add_signext_91 = $signed({{5{product48[20]}}, product48});
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum46 = add_temp_45[25:0];

  assign add_signext_92 = sum46;
  assign add_signext_93 = $signed({{5{product49[20]}}, product49});
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum47 = add_temp_46[25:0];

  assign add_signext_94 = sum47;
  assign add_signext_95 = $signed({{5{product50[20]}}, product50});
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum48 = add_temp_47[25:0];

  assign add_signext_96 = sum48;
  assign add_signext_97 = $signed({{5{product51[20]}}, product51});
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum49 = add_temp_48[25:0];

  assign add_signext_98 = sum49;
  assign add_signext_99 = $signed({{5{product52[20]}}, product52});
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum50 = add_temp_49[25:0];

  assign add_signext_100 = sum50;
  assign add_signext_101 = $signed({{5{product53[20]}}, product53});
  assign add_temp_50 = add_signext_100 + add_signext_101;
  assign sum51 = add_temp_50[25:0];

  assign add_signext_102 = sum51;
  assign add_signext_103 = $signed({{5{product54[20]}}, product54});
  assign add_temp_51 = add_signext_102 + add_signext_103;
  assign sum52 = add_temp_51[25:0];

  assign add_signext_104 = sum52;
  assign add_signext_105 = $signed({{5{product55[20]}}, product55});
  assign add_temp_52 = add_signext_104 + add_signext_105;
  assign sum53 = add_temp_52[25:0];

  assign add_signext_106 = sum53;
  assign add_signext_107 = $signed({{5{product56[20]}}, product56});
  assign add_temp_53 = add_signext_106 + add_signext_107;
  assign sum54 = add_temp_53[25:0];

  assign add_signext_108 = sum54;
  assign add_signext_109 = $signed({{5{product57[20]}}, product57});
  assign add_temp_54 = add_signext_108 + add_signext_109;
  assign sum55 = add_temp_54[25:0];

  assign add_signext_110 = sum55;
  assign add_signext_111 = $signed({{5{product58[20]}}, product58});
  assign add_temp_55 = add_signext_110 + add_signext_111;
  assign sum56 = add_temp_55[25:0];

  assign add_signext_112 = sum56;
  assign add_signext_113 = $signed({{5{product59[20]}}, product59});
  assign add_temp_56 = add_signext_112 + add_signext_113;
  assign sum57 = add_temp_56[25:0];

  assign add_signext_114 = sum57;
  assign add_signext_115 = $signed({{5{product60[20]}}, product60});
  assign add_temp_57 = add_signext_114 + add_signext_115;
  assign sum58 = add_temp_57[25:0];

  assign add_signext_116 = sum58;
  assign add_signext_117 = $signed({{5{product61[20]}}, product61});
  assign add_temp_58 = add_signext_116 + add_signext_117;
  assign sum59 = add_temp_58[25:0];

  assign add_signext_118 = sum59;
  assign add_signext_119 = $signed({{5{product62[20]}}, product62});
  assign add_temp_59 = add_signext_118 + add_signext_119;
  assign sum60 = add_temp_59[25:0];

  assign add_signext_120 = sum60;
  assign add_signext_121 = $signed({{5{product63[20]}}, product63});
  assign add_temp_60 = add_signext_120 + add_signext_121;
  assign sum61 = add_temp_60[25:0];

  assign add_signext_122 = sum61;
  assign add_signext_123 = $signed({{5{product64[20]}}, product64});
  assign add_temp_61 = add_signext_122 + add_signext_123;
  assign sum62 = add_temp_61[25:0];

  assign add_signext_124 = sum62;
  assign add_signext_125 = $signed({{5{product65[20]}}, product65});
  assign add_temp_62 = add_signext_124 + add_signext_125;
  assign sum63 = add_temp_62[25:0];

  assign add_signext_126 = sum63;
  assign add_signext_127 = $signed({{5{product66[20]}}, product66});
  assign add_temp_63 = add_signext_126 + add_signext_127;
  assign sum64 = add_temp_63[25:0];

  assign add_signext_128 = sum64;
  assign add_signext_129 = $signed({{5{product67[20]}}, product67});
  assign add_temp_64 = add_signext_128 + add_signext_129;
  assign sum65 = add_temp_64[25:0];

  assign add_signext_130 = sum65;
  assign add_signext_131 = $signed({{5{product68[20]}}, product68});
  assign add_temp_65 = add_signext_130 + add_signext_131;
  assign sum66 = add_temp_65[25:0];

  assign add_signext_132 = sum66;
  assign add_signext_133 = $signed({{5{product69[20]}}, product69});
  assign add_temp_66 = add_signext_132 + add_signext_133;
  assign sum67 = add_temp_66[25:0];

  assign add_signext_134 = sum67;
  assign add_signext_135 = $signed({{5{product70[20]}}, product70});
  assign add_temp_67 = add_signext_134 + add_signext_135;
  assign sum68 = add_temp_67[25:0];

  assign add_signext_136 = sum68;
  assign add_signext_137 = $signed({{5{product71[20]}}, product71});
  assign add_temp_68 = add_signext_136 + add_signext_137;
  assign sum69 = add_temp_68[25:0];

  assign add_signext_138 = sum69;
  assign add_signext_139 = $signed({{5{product72[20]}}, product72});
  assign add_temp_69 = add_signext_138 + add_signext_139;
  assign sum70 = add_temp_69[25:0];

  assign add_signext_140 = sum70;
  assign add_signext_141 = $signed({{5{product73[20]}}, product73});
  assign add_temp_70 = add_signext_140 + add_signext_141;
  assign sum71 = add_temp_70[25:0];

  assign add_signext_142 = sum71;
  assign add_signext_143 = $signed({{5{product74[20]}}, product74});
  assign add_temp_71 = add_signext_142 + add_signext_143;
  assign sum72 = add_temp_71[25:0];

  assign add_signext_144 = sum72;
  assign add_signext_145 = $signed({{5{product75[20]}}, product75});
  assign add_temp_72 = add_signext_144 + add_signext_145;
  assign sum73 = add_temp_72[25:0];

  assign add_signext_146 = sum73;
  assign add_signext_147 = $signed({{5{product76[20]}}, product76});
  assign add_temp_73 = add_signext_146 + add_signext_147;
  assign sum74 = add_temp_73[25:0];

  assign add_signext_148 = sum74;
  assign add_signext_149 = $signed({{5{product77[20]}}, product77});
  assign add_temp_74 = add_signext_148 + add_signext_149;
  assign sum75 = add_temp_74[25:0];

  assign add_signext_150 = sum75;
  assign add_signext_151 = $signed({{5{product78[20]}}, product78});
  assign add_temp_75 = add_signext_150 + add_signext_151;
  assign sum76 = add_temp_75[25:0];

  assign add_signext_152 = sum76;
  assign add_signext_153 = $signed({{5{product79[20]}}, product79});
  assign add_temp_76 = add_signext_152 + add_signext_153;
  assign sum77 = add_temp_76[25:0];

  assign add_signext_154 = sum77;
  assign add_signext_155 = $signed({{5{product80[20]}}, product80});
  assign add_temp_77 = add_signext_154 + add_signext_155;
  assign sum78 = add_temp_77[25:0];

  assign add_signext_156 = sum78;
  assign add_signext_157 = $signed({{5{product81[20]}}, product81});
  assign add_temp_78 = add_signext_156 + add_signext_157;
  assign sum79 = add_temp_78[25:0];

  assign add_signext_158 = sum79;
  assign add_signext_159 = $signed({{5{product82[20]}}, product82});
  assign add_temp_79 = add_signext_158 + add_signext_159;
  assign sum80 = add_temp_79[25:0];

  assign add_signext_160 = sum80;
  assign add_signext_161 = $signed({{5{product83[20]}}, product83});
  assign add_temp_80 = add_signext_160 + add_signext_161;
  assign sum81 = add_temp_80[25:0];

  assign add_signext_162 = sum81;
  assign add_signext_163 = $signed({{5{product84[20]}}, product84});
  assign add_temp_81 = add_signext_162 + add_signext_163;
  assign sum82 = add_temp_81[25:0];

  assign add_signext_164 = sum82;
  assign add_signext_165 = $signed({{5{product85[20]}}, product85});
  assign add_temp_82 = add_signext_164 + add_signext_165;
  assign sum83 = add_temp_82[25:0];

  assign add_signext_166 = sum83;
  assign add_signext_167 = $signed({{5{product87[20]}}, product87});
  assign add_temp_83 = add_signext_166 + add_signext_167;
  assign sum84 = add_temp_83[25:0];

  assign add_signext_168 = sum84;
  assign add_signext_169 = $signed({{5{product88[20]}}, product88});
  assign add_temp_84 = add_signext_168 + add_signext_169;
  assign sum85 = add_temp_84[25:0];

  assign add_signext_170 = sum85;
  assign add_signext_171 = $signed({{5{product89[20]}}, product89});
  assign add_temp_85 = add_signext_170 + add_signext_171;
  assign sum86 = add_temp_85[25:0];

  assign add_signext_172 = sum86;
  assign add_signext_173 = $signed({{5{product90[20]}}, product90});
  assign add_temp_86 = add_signext_172 + add_signext_173;
  assign sum87 = add_temp_86[25:0];

  assign add_signext_174 = sum87;
  assign add_signext_175 = $signed({{5{product91[20]}}, product91});
  assign add_temp_87 = add_signext_174 + add_signext_175;
  assign sum88 = add_temp_87[25:0];

  assign add_signext_176 = sum88;
  assign add_signext_177 = $signed({{5{product92[20]}}, product92});
  assign add_temp_88 = add_signext_176 + add_signext_177;
  assign sum89 = add_temp_88[25:0];

  assign add_signext_178 = sum89;
  assign add_signext_179 = $signed({{5{product93[20]}}, product93});
  assign add_temp_89 = add_signext_178 + add_signext_179;
  assign sum90 = add_temp_89[25:0];

  assign add_signext_180 = sum90;
  assign add_signext_181 = $signed({{5{product94[20]}}, product94});
  assign add_temp_90 = add_signext_180 + add_signext_181;
  assign sum91 = add_temp_90[25:0];

  assign add_signext_182 = sum91;
  assign add_signext_183 = $signed({{5{product95[20]}}, product95});
  assign add_temp_91 = add_signext_182 + add_signext_183;
  assign sum92 = add_temp_91[25:0];

  assign add_signext_184 = sum92;
  assign add_signext_185 = $signed({{5{product96[20]}}, product96});
  assign add_temp_92 = add_signext_184 + add_signext_185;
  assign sum93 = add_temp_92[25:0];

  assign add_signext_186 = sum93;
  assign add_signext_187 = $signed({{5{product97[20]}}, product97});
  assign add_temp_93 = add_signext_186 + add_signext_187;
  assign sum94 = add_temp_93[25:0];

  assign add_signext_188 = sum94;
  assign add_signext_189 = $signed({{5{product98[20]}}, product98});
  assign add_temp_94 = add_signext_188 + add_signext_189;
  assign sum95 = add_temp_94[25:0];

  assign add_signext_190 = sum95;
  assign add_signext_191 = $signed({{5{product99[20]}}, product99});
  assign add_temp_95 = add_signext_190 + add_signext_191;
  assign sum96 = add_temp_95[25:0];

  assign add_signext_192 = sum96;
  assign add_signext_193 = $signed({{5{product100[20]}}, product100});
  assign add_temp_96 = add_signext_192 + add_signext_193;
  assign sum97 = add_temp_96[25:0];

  assign add_signext_194 = sum97;
  assign add_signext_195 = $signed({{5{product101[20]}}, product101});
  assign add_temp_97 = add_signext_194 + add_signext_195;
  assign sum98 = add_temp_97[25:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum98;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // Lowpass_1_MHz_V3
