// -------------------------------------------------------------
//
// Module: Lowpass_5_MHz_V2
// Generated by MATLAB(R) 9.14 and Filter Design HDL Coder 3.1.13.
// Generated on: 2023-06-13 14:32:56
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// OptimizeForHDL: on
// TargetDirectory: F:\Heavy_Software\Quartus_Prime_13.1\quartus\proyek
// EDAScriptGeneration: off
// Name: Lowpass_5_MHz_V2
// TargetLanguage: Verilog
// TestBenchName: Hlp_tb
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// Filter Specifications:
//
// Sample Rate     : 50 MHz
// Response        : Lowpass
// Specification   : N,Fst,Ap,Ast
// Stopband Atten. : 80 dB
// Passband Ripple : 1 dB
// Filter Order    : 100
// Stopband Edge   : 5 MHz
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 101
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s14,15 -> [-2.500000e-01 2.500000e-01)
// Input             : s14,0 -> [-8192 8192)
// Filter Internals  : Full Precision
//   Output          : s30,15 -> [-16384 16384)  (auto determined)
//   Product         : s27,15 -> [-2048 2048)  (auto determined)
//   Accumulator     : s30,15 -> [-16384 16384)  (auto determined)
//   Round Mode      : No rounding
//   Overflow Mode   : No overflow
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module Lowpass_5_MHz_V2
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [13:0] filter_in; //sfix14
  output  signed [29:0] filter_out; //sfix30_En15

////////////////////////////////////////////////////////////////
//Module Architecture: Lowpass_5_MHz_V2
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [13:0] coeff1 = 14'b00000000000000; //sfix14_En15
  parameter signed [13:0] coeff2 = 14'b00000000000110; //sfix14_En15
  parameter signed [13:0] coeff3 = 14'b00000000010000; //sfix14_En15
  parameter signed [13:0] coeff4 = 14'b00000000100010; //sfix14_En15
  parameter signed [13:0] coeff5 = 14'b00000000111011; //sfix14_En15
  parameter signed [13:0] coeff6 = 14'b00000001011011; //sfix14_En15
  parameter signed [13:0] coeff7 = 14'b00000001111111; //sfix14_En15
  parameter signed [13:0] coeff8 = 14'b00000010100000; //sfix14_En15
  parameter signed [13:0] coeff9 = 14'b00000010111000; //sfix14_En15
  parameter signed [13:0] coeff10 = 14'b00000010111111; //sfix14_En15
  parameter signed [13:0] coeff11 = 14'b00000010101111; //sfix14_En15
  parameter signed [13:0] coeff12 = 14'b00000010000110; //sfix14_En15
  parameter signed [13:0] coeff13 = 14'b00000001000110; //sfix14_En15
  parameter signed [13:0] coeff14 = 14'b11111111111001; //sfix14_En15
  parameter signed [13:0] coeff15 = 14'b11111110101100; //sfix14_En15
  parameter signed [13:0] coeff16 = 14'b11111101101111; //sfix14_En15
  parameter signed [13:0] coeff17 = 14'b11111101010001; //sfix14_En15
  parameter signed [13:0] coeff18 = 14'b11111101011101; //sfix14_En15
  parameter signed [13:0] coeff19 = 14'b11111110010100; //sfix14_En15
  parameter signed [13:0] coeff20 = 14'b11111111101101; //sfix14_En15
  parameter signed [13:0] coeff21 = 14'b00000001010110; //sfix14_En15
  parameter signed [13:0] coeff22 = 14'b00000010110101; //sfix14_En15
  parameter signed [13:0] coeff23 = 14'b00000011110000; //sfix14_En15
  parameter signed [13:0] coeff24 = 14'b00000011110010; //sfix14_En15
  parameter signed [13:0] coeff25 = 14'b00000010110011; //sfix14_En15
  parameter signed [13:0] coeff26 = 14'b00000000111010; //sfix14_En15
  parameter signed [13:0] coeff27 = 14'b11111110100000; //sfix14_En15
  parameter signed [13:0] coeff28 = 14'b11111100001011; //sfix14_En15
  parameter signed [13:0] coeff29 = 14'b11111010100010; //sfix14_En15
  parameter signed [13:0] coeff30 = 14'b11111010001010; //sfix14_En15
  parameter signed [13:0] coeff31 = 14'b11111011010101; //sfix14_En15
  parameter signed [13:0] coeff32 = 14'b11111101111111; //sfix14_En15
  parameter signed [13:0] coeff33 = 14'b00000001101000; //sfix14_En15
  parameter signed [13:0] coeff34 = 14'b00000101011010; //sfix14_En15
  parameter signed [13:0] coeff35 = 14'b00001000010101; //sfix14_En15
  parameter signed [13:0] coeff36 = 14'b00001001011011; //sfix14_En15
  parameter signed [13:0] coeff37 = 14'b00001000000011; //sfix14_En15
  parameter signed [13:0] coeff38 = 14'b00000100001010; //sfix14_En15
  parameter signed [13:0] coeff39 = 14'b11111110010010; //sfix14_En15
  parameter signed [13:0] coeff40 = 14'b11110111101001; //sfix14_En15
  parameter signed [13:0] coeff41 = 14'b11110001111000; //sfix14_En15
  parameter signed [13:0] coeff42 = 14'b11101110110011; //sfix14_En15
  parameter signed [13:0] coeff43 = 14'b11101111111100; //sfix14_En15
  parameter signed [13:0] coeff44 = 14'b11110110010000; //sfix14_En15
  parameter signed [13:0] coeff45 = 14'b00000001110010; //sfix14_En15
  parameter signed [13:0] coeff46 = 14'b00010001100110; //sfix14_En15
  parameter signed [13:0] coeff47 = 14'b00100011110101; //sfix14_En15
  parameter signed [13:0] coeff48 = 14'b00110110000001; //sfix14_En15
  parameter signed [13:0] coeff49 = 14'b01000101100000; //sfix14_En15
  parameter signed [13:0] coeff50 = 14'b01001111111000; //sfix14_En15
  parameter signed [13:0] coeff51 = 14'b01010011100010; //sfix14_En15
  parameter signed [13:0] coeff52 = 14'b01001111111000; //sfix14_En15
  parameter signed [13:0] coeff53 = 14'b01000101100000; //sfix14_En15
  parameter signed [13:0] coeff54 = 14'b00110110000001; //sfix14_En15
  parameter signed [13:0] coeff55 = 14'b00100011110101; //sfix14_En15
  parameter signed [13:0] coeff56 = 14'b00010001100110; //sfix14_En15
  parameter signed [13:0] coeff57 = 14'b00000001110010; //sfix14_En15
  parameter signed [13:0] coeff58 = 14'b11110110010000; //sfix14_En15
  parameter signed [13:0] coeff59 = 14'b11101111111100; //sfix14_En15
  parameter signed [13:0] coeff60 = 14'b11101110110011; //sfix14_En15
  parameter signed [13:0] coeff61 = 14'b11110001111000; //sfix14_En15
  parameter signed [13:0] coeff62 = 14'b11110111101001; //sfix14_En15
  parameter signed [13:0] coeff63 = 14'b11111110010010; //sfix14_En15
  parameter signed [13:0] coeff64 = 14'b00000100001010; //sfix14_En15
  parameter signed [13:0] coeff65 = 14'b00001000000011; //sfix14_En15
  parameter signed [13:0] coeff66 = 14'b00001001011011; //sfix14_En15
  parameter signed [13:0] coeff67 = 14'b00001000010101; //sfix14_En15
  parameter signed [13:0] coeff68 = 14'b00000101011010; //sfix14_En15
  parameter signed [13:0] coeff69 = 14'b00000001101000; //sfix14_En15
  parameter signed [13:0] coeff70 = 14'b11111101111111; //sfix14_En15
  parameter signed [13:0] coeff71 = 14'b11111011010101; //sfix14_En15
  parameter signed [13:0] coeff72 = 14'b11111010001010; //sfix14_En15
  parameter signed [13:0] coeff73 = 14'b11111010100010; //sfix14_En15
  parameter signed [13:0] coeff74 = 14'b11111100001011; //sfix14_En15
  parameter signed [13:0] coeff75 = 14'b11111110100000; //sfix14_En15
  parameter signed [13:0] coeff76 = 14'b00000000111010; //sfix14_En15
  parameter signed [13:0] coeff77 = 14'b00000010110011; //sfix14_En15
  parameter signed [13:0] coeff78 = 14'b00000011110010; //sfix14_En15
  parameter signed [13:0] coeff79 = 14'b00000011110000; //sfix14_En15
  parameter signed [13:0] coeff80 = 14'b00000010110101; //sfix14_En15
  parameter signed [13:0] coeff81 = 14'b00000001010110; //sfix14_En15
  parameter signed [13:0] coeff82 = 14'b11111111101101; //sfix14_En15
  parameter signed [13:0] coeff83 = 14'b11111110010100; //sfix14_En15
  parameter signed [13:0] coeff84 = 14'b11111101011101; //sfix14_En15
  parameter signed [13:0] coeff85 = 14'b11111101010001; //sfix14_En15
  parameter signed [13:0] coeff86 = 14'b11111101101111; //sfix14_En15
  parameter signed [13:0] coeff87 = 14'b11111110101100; //sfix14_En15
  parameter signed [13:0] coeff88 = 14'b11111111111001; //sfix14_En15
  parameter signed [13:0] coeff89 = 14'b00000001000110; //sfix14_En15
  parameter signed [13:0] coeff90 = 14'b00000010000110; //sfix14_En15
  parameter signed [13:0] coeff91 = 14'b00000010101111; //sfix14_En15
  parameter signed [13:0] coeff92 = 14'b00000010111111; //sfix14_En15
  parameter signed [13:0] coeff93 = 14'b00000010111000; //sfix14_En15
  parameter signed [13:0] coeff94 = 14'b00000010100000; //sfix14_En15
  parameter signed [13:0] coeff95 = 14'b00000001111111; //sfix14_En15
  parameter signed [13:0] coeff96 = 14'b00000001011011; //sfix14_En15
  parameter signed [13:0] coeff97 = 14'b00000000111011; //sfix14_En15
  parameter signed [13:0] coeff98 = 14'b00000000100010; //sfix14_En15
  parameter signed [13:0] coeff99 = 14'b00000000010000; //sfix14_En15
  parameter signed [13:0] coeff100 = 14'b00000000000110; //sfix14_En15
  parameter signed [13:0] coeff101 = 14'b00000000000000; //sfix14_En15

  // Signals
  reg  signed [13:0] delay_pipeline [0:100] ; // sfix14
  wire signed [26:0] product100; // sfix27_En15
  wire signed [27:0] mul_temp; // sfix28_En15
  wire signed [26:0] product99; // sfix27_En15
  wire signed [26:0] product98; // sfix27_En15
  wire signed [27:0] mul_temp_1; // sfix28_En15
  wire signed [26:0] product97; // sfix27_En15
  wire signed [27:0] mul_temp_2; // sfix28_En15
  wire signed [26:0] product96; // sfix27_En15
  wire signed [27:0] mul_temp_3; // sfix28_En15
  wire signed [26:0] product95; // sfix27_En15
  wire signed [27:0] mul_temp_4; // sfix28_En15
  wire signed [26:0] product94; // sfix27_En15
  wire signed [27:0] mul_temp_5; // sfix28_En15
  wire signed [26:0] product93; // sfix27_En15
  wire signed [27:0] mul_temp_6; // sfix28_En15
  wire signed [26:0] product92; // sfix27_En15
  wire signed [27:0] mul_temp_7; // sfix28_En15
  wire signed [26:0] product91; // sfix27_En15
  wire signed [27:0] mul_temp_8; // sfix28_En15
  wire signed [26:0] product90; // sfix27_En15
  wire signed [27:0] mul_temp_9; // sfix28_En15
  wire signed [26:0] product89; // sfix27_En15
  wire signed [27:0] mul_temp_10; // sfix28_En15
  wire signed [26:0] product88; // sfix27_En15
  wire signed [27:0] mul_temp_11; // sfix28_En15
  wire signed [26:0] product87; // sfix27_En15
  wire signed [27:0] mul_temp_12; // sfix28_En15
  wire signed [26:0] product86; // sfix27_En15
  wire signed [27:0] mul_temp_13; // sfix28_En15
  wire signed [26:0] product85; // sfix27_En15
  wire signed [27:0] mul_temp_14; // sfix28_En15
  wire signed [26:0] product84; // sfix27_En15
  wire signed [27:0] mul_temp_15; // sfix28_En15
  wire signed [26:0] product83; // sfix27_En15
  wire signed [27:0] mul_temp_16; // sfix28_En15
  wire signed [26:0] product82; // sfix27_En15
  wire signed [27:0] mul_temp_17; // sfix28_En15
  wire signed [26:0] product81; // sfix27_En15
  wire signed [27:0] mul_temp_18; // sfix28_En15
  wire signed [26:0] product80; // sfix27_En15
  wire signed [27:0] mul_temp_19; // sfix28_En15
  wire signed [26:0] product79; // sfix27_En15
  wire signed [27:0] mul_temp_20; // sfix28_En15
  wire signed [26:0] product78; // sfix27_En15
  wire signed [27:0] mul_temp_21; // sfix28_En15
  wire signed [26:0] product77; // sfix27_En15
  wire signed [27:0] mul_temp_22; // sfix28_En15
  wire signed [26:0] product76; // sfix27_En15
  wire signed [27:0] mul_temp_23; // sfix28_En15
  wire signed [26:0] product75; // sfix27_En15
  wire signed [27:0] mul_temp_24; // sfix28_En15
  wire signed [26:0] product74; // sfix27_En15
  wire signed [27:0] mul_temp_25; // sfix28_En15
  wire signed [26:0] product73; // sfix27_En15
  wire signed [27:0] mul_temp_26; // sfix28_En15
  wire signed [26:0] product72; // sfix27_En15
  wire signed [27:0] mul_temp_27; // sfix28_En15
  wire signed [26:0] product71; // sfix27_En15
  wire signed [27:0] mul_temp_28; // sfix28_En15
  wire signed [26:0] product70; // sfix27_En15
  wire signed [27:0] mul_temp_29; // sfix28_En15
  wire signed [26:0] product69; // sfix27_En15
  wire signed [27:0] mul_temp_30; // sfix28_En15
  wire signed [26:0] product68; // sfix27_En15
  wire signed [27:0] mul_temp_31; // sfix28_En15
  wire signed [26:0] product67; // sfix27_En15
  wire signed [27:0] mul_temp_32; // sfix28_En15
  wire signed [26:0] product66; // sfix27_En15
  wire signed [27:0] mul_temp_33; // sfix28_En15
  wire signed [26:0] product65; // sfix27_En15
  wire signed [27:0] mul_temp_34; // sfix28_En15
  wire signed [26:0] product64; // sfix27_En15
  wire signed [27:0] mul_temp_35; // sfix28_En15
  wire signed [26:0] product63; // sfix27_En15
  wire signed [27:0] mul_temp_36; // sfix28_En15
  wire signed [26:0] product62; // sfix27_En15
  wire signed [27:0] mul_temp_37; // sfix28_En15
  wire signed [26:0] product61; // sfix27_En15
  wire signed [27:0] mul_temp_38; // sfix28_En15
  wire signed [26:0] product60; // sfix27_En15
  wire signed [27:0] mul_temp_39; // sfix28_En15
  wire signed [26:0] product59; // sfix27_En15
  wire signed [27:0] mul_temp_40; // sfix28_En15
  wire signed [26:0] product58; // sfix27_En15
  wire signed [27:0] mul_temp_41; // sfix28_En15
  wire signed [26:0] product57; // sfix27_En15
  wire signed [27:0] mul_temp_42; // sfix28_En15
  wire signed [26:0] product56; // sfix27_En15
  wire signed [27:0] mul_temp_43; // sfix28_En15
  wire signed [26:0] product55; // sfix27_En15
  wire signed [27:0] mul_temp_44; // sfix28_En15
  wire signed [26:0] product54; // sfix27_En15
  wire signed [27:0] mul_temp_45; // sfix28_En15
  wire signed [26:0] product53; // sfix27_En15
  wire signed [27:0] mul_temp_46; // sfix28_En15
  wire signed [26:0] product52; // sfix27_En15
  wire signed [27:0] mul_temp_47; // sfix28_En15
  wire signed [26:0] product51; // sfix27_En15
  wire signed [27:0] mul_temp_48; // sfix28_En15
  wire signed [26:0] product50; // sfix27_En15
  wire signed [27:0] mul_temp_49; // sfix28_En15
  wire signed [26:0] product49; // sfix27_En15
  wire signed [27:0] mul_temp_50; // sfix28_En15
  wire signed [26:0] product48; // sfix27_En15
  wire signed [27:0] mul_temp_51; // sfix28_En15
  wire signed [26:0] product47; // sfix27_En15
  wire signed [27:0] mul_temp_52; // sfix28_En15
  wire signed [26:0] product46; // sfix27_En15
  wire signed [27:0] mul_temp_53; // sfix28_En15
  wire signed [26:0] product45; // sfix27_En15
  wire signed [27:0] mul_temp_54; // sfix28_En15
  wire signed [26:0] product44; // sfix27_En15
  wire signed [27:0] mul_temp_55; // sfix28_En15
  wire signed [26:0] product43; // sfix27_En15
  wire signed [27:0] mul_temp_56; // sfix28_En15
  wire signed [26:0] product42; // sfix27_En15
  wire signed [27:0] mul_temp_57; // sfix28_En15
  wire signed [26:0] product41; // sfix27_En15
  wire signed [27:0] mul_temp_58; // sfix28_En15
  wire signed [26:0] product40; // sfix27_En15
  wire signed [27:0] mul_temp_59; // sfix28_En15
  wire signed [26:0] product39; // sfix27_En15
  wire signed [27:0] mul_temp_60; // sfix28_En15
  wire signed [26:0] product38; // sfix27_En15
  wire signed [27:0] mul_temp_61; // sfix28_En15
  wire signed [26:0] product37; // sfix27_En15
  wire signed [27:0] mul_temp_62; // sfix28_En15
  wire signed [26:0] product36; // sfix27_En15
  wire signed [27:0] mul_temp_63; // sfix28_En15
  wire signed [26:0] product35; // sfix27_En15
  wire signed [27:0] mul_temp_64; // sfix28_En15
  wire signed [26:0] product34; // sfix27_En15
  wire signed [27:0] mul_temp_65; // sfix28_En15
  wire signed [26:0] product33; // sfix27_En15
  wire signed [27:0] mul_temp_66; // sfix28_En15
  wire signed [26:0] product32; // sfix27_En15
  wire signed [27:0] mul_temp_67; // sfix28_En15
  wire signed [26:0] product31; // sfix27_En15
  wire signed [27:0] mul_temp_68; // sfix28_En15
  wire signed [26:0] product30; // sfix27_En15
  wire signed [27:0] mul_temp_69; // sfix28_En15
  wire signed [26:0] product29; // sfix27_En15
  wire signed [27:0] mul_temp_70; // sfix28_En15
  wire signed [26:0] product28; // sfix27_En15
  wire signed [27:0] mul_temp_71; // sfix28_En15
  wire signed [26:0] product27; // sfix27_En15
  wire signed [27:0] mul_temp_72; // sfix28_En15
  wire signed [26:0] product26; // sfix27_En15
  wire signed [27:0] mul_temp_73; // sfix28_En15
  wire signed [26:0] product25; // sfix27_En15
  wire signed [27:0] mul_temp_74; // sfix28_En15
  wire signed [26:0] product24; // sfix27_En15
  wire signed [27:0] mul_temp_75; // sfix28_En15
  wire signed [26:0] product23; // sfix27_En15
  wire signed [27:0] mul_temp_76; // sfix28_En15
  wire signed [26:0] product22; // sfix27_En15
  wire signed [27:0] mul_temp_77; // sfix28_En15
  wire signed [26:0] product21; // sfix27_En15
  wire signed [27:0] mul_temp_78; // sfix28_En15
  wire signed [26:0] product20; // sfix27_En15
  wire signed [27:0] mul_temp_79; // sfix28_En15
  wire signed [26:0] product19; // sfix27_En15
  wire signed [27:0] mul_temp_80; // sfix28_En15
  wire signed [26:0] product18; // sfix27_En15
  wire signed [27:0] mul_temp_81; // sfix28_En15
  wire signed [26:0] product17; // sfix27_En15
  wire signed [27:0] mul_temp_82; // sfix28_En15
  wire signed [26:0] product16; // sfix27_En15
  wire signed [27:0] mul_temp_83; // sfix28_En15
  wire signed [26:0] product15; // sfix27_En15
  wire signed [27:0] mul_temp_84; // sfix28_En15
  wire signed [26:0] product14; // sfix27_En15
  wire signed [27:0] mul_temp_85; // sfix28_En15
  wire signed [26:0] product13; // sfix27_En15
  wire signed [27:0] mul_temp_86; // sfix28_En15
  wire signed [26:0] product12; // sfix27_En15
  wire signed [27:0] mul_temp_87; // sfix28_En15
  wire signed [26:0] product11; // sfix27_En15
  wire signed [27:0] mul_temp_88; // sfix28_En15
  wire signed [26:0] product10; // sfix27_En15
  wire signed [27:0] mul_temp_89; // sfix28_En15
  wire signed [26:0] product9; // sfix27_En15
  wire signed [27:0] mul_temp_90; // sfix28_En15
  wire signed [26:0] product8; // sfix27_En15
  wire signed [27:0] mul_temp_91; // sfix28_En15
  wire signed [26:0] product7; // sfix27_En15
  wire signed [27:0] mul_temp_92; // sfix28_En15
  wire signed [26:0] product6; // sfix27_En15
  wire signed [27:0] mul_temp_93; // sfix28_En15
  wire signed [26:0] product5; // sfix27_En15
  wire signed [27:0] mul_temp_94; // sfix28_En15
  wire signed [26:0] product4; // sfix27_En15
  wire signed [27:0] mul_temp_95; // sfix28_En15
  wire signed [26:0] product3; // sfix27_En15
  wire signed [26:0] product2; // sfix27_En15
  wire signed [27:0] mul_temp_96; // sfix28_En15
  wire signed [29:0] sum1; // sfix30_En15
  wire signed [26:0] add_signext; // sfix27_En15
  wire signed [26:0] add_signext_1; // sfix27_En15
  wire signed [27:0] add_temp; // sfix28_En15
  wire signed [29:0] sum2; // sfix30_En15
  wire signed [29:0] add_signext_2; // sfix30_En15
  wire signed [29:0] add_signext_3; // sfix30_En15
  wire signed [30:0] add_temp_1; // sfix31_En15
  wire signed [29:0] sum3; // sfix30_En15
  wire signed [29:0] add_signext_4; // sfix30_En15
  wire signed [29:0] add_signext_5; // sfix30_En15
  wire signed [30:0] add_temp_2; // sfix31_En15
  wire signed [29:0] sum4; // sfix30_En15
  wire signed [29:0] add_signext_6; // sfix30_En15
  wire signed [29:0] add_signext_7; // sfix30_En15
  wire signed [30:0] add_temp_3; // sfix31_En15
  wire signed [29:0] sum5; // sfix30_En15
  wire signed [29:0] add_signext_8; // sfix30_En15
  wire signed [29:0] add_signext_9; // sfix30_En15
  wire signed [30:0] add_temp_4; // sfix31_En15
  wire signed [29:0] sum6; // sfix30_En15
  wire signed [29:0] add_signext_10; // sfix30_En15
  wire signed [29:0] add_signext_11; // sfix30_En15
  wire signed [30:0] add_temp_5; // sfix31_En15
  wire signed [29:0] sum7; // sfix30_En15
  wire signed [29:0] add_signext_12; // sfix30_En15
  wire signed [29:0] add_signext_13; // sfix30_En15
  wire signed [30:0] add_temp_6; // sfix31_En15
  wire signed [29:0] sum8; // sfix30_En15
  wire signed [29:0] add_signext_14; // sfix30_En15
  wire signed [29:0] add_signext_15; // sfix30_En15
  wire signed [30:0] add_temp_7; // sfix31_En15
  wire signed [29:0] sum9; // sfix30_En15
  wire signed [29:0] add_signext_16; // sfix30_En15
  wire signed [29:0] add_signext_17; // sfix30_En15
  wire signed [30:0] add_temp_8; // sfix31_En15
  wire signed [29:0] sum10; // sfix30_En15
  wire signed [29:0] add_signext_18; // sfix30_En15
  wire signed [29:0] add_signext_19; // sfix30_En15
  wire signed [30:0] add_temp_9; // sfix31_En15
  wire signed [29:0] sum11; // sfix30_En15
  wire signed [29:0] add_signext_20; // sfix30_En15
  wire signed [29:0] add_signext_21; // sfix30_En15
  wire signed [30:0] add_temp_10; // sfix31_En15
  wire signed [29:0] sum12; // sfix30_En15
  wire signed [29:0] add_signext_22; // sfix30_En15
  wire signed [29:0] add_signext_23; // sfix30_En15
  wire signed [30:0] add_temp_11; // sfix31_En15
  wire signed [29:0] sum13; // sfix30_En15
  wire signed [29:0] add_signext_24; // sfix30_En15
  wire signed [29:0] add_signext_25; // sfix30_En15
  wire signed [30:0] add_temp_12; // sfix31_En15
  wire signed [29:0] sum14; // sfix30_En15
  wire signed [29:0] add_signext_26; // sfix30_En15
  wire signed [29:0] add_signext_27; // sfix30_En15
  wire signed [30:0] add_temp_13; // sfix31_En15
  wire signed [29:0] sum15; // sfix30_En15
  wire signed [29:0] add_signext_28; // sfix30_En15
  wire signed [29:0] add_signext_29; // sfix30_En15
  wire signed [30:0] add_temp_14; // sfix31_En15
  wire signed [29:0] sum16; // sfix30_En15
  wire signed [29:0] add_signext_30; // sfix30_En15
  wire signed [29:0] add_signext_31; // sfix30_En15
  wire signed [30:0] add_temp_15; // sfix31_En15
  wire signed [29:0] sum17; // sfix30_En15
  wire signed [29:0] add_signext_32; // sfix30_En15
  wire signed [29:0] add_signext_33; // sfix30_En15
  wire signed [30:0] add_temp_16; // sfix31_En15
  wire signed [29:0] sum18; // sfix30_En15
  wire signed [29:0] add_signext_34; // sfix30_En15
  wire signed [29:0] add_signext_35; // sfix30_En15
  wire signed [30:0] add_temp_17; // sfix31_En15
  wire signed [29:0] sum19; // sfix30_En15
  wire signed [29:0] add_signext_36; // sfix30_En15
  wire signed [29:0] add_signext_37; // sfix30_En15
  wire signed [30:0] add_temp_18; // sfix31_En15
  wire signed [29:0] sum20; // sfix30_En15
  wire signed [29:0] add_signext_38; // sfix30_En15
  wire signed [29:0] add_signext_39; // sfix30_En15
  wire signed [30:0] add_temp_19; // sfix31_En15
  wire signed [29:0] sum21; // sfix30_En15
  wire signed [29:0] add_signext_40; // sfix30_En15
  wire signed [29:0] add_signext_41; // sfix30_En15
  wire signed [30:0] add_temp_20; // sfix31_En15
  wire signed [29:0] sum22; // sfix30_En15
  wire signed [29:0] add_signext_42; // sfix30_En15
  wire signed [29:0] add_signext_43; // sfix30_En15
  wire signed [30:0] add_temp_21; // sfix31_En15
  wire signed [29:0] sum23; // sfix30_En15
  wire signed [29:0] add_signext_44; // sfix30_En15
  wire signed [29:0] add_signext_45; // sfix30_En15
  wire signed [30:0] add_temp_22; // sfix31_En15
  wire signed [29:0] sum24; // sfix30_En15
  wire signed [29:0] add_signext_46; // sfix30_En15
  wire signed [29:0] add_signext_47; // sfix30_En15
  wire signed [30:0] add_temp_23; // sfix31_En15
  wire signed [29:0] sum25; // sfix30_En15
  wire signed [29:0] add_signext_48; // sfix30_En15
  wire signed [29:0] add_signext_49; // sfix30_En15
  wire signed [30:0] add_temp_24; // sfix31_En15
  wire signed [29:0] sum26; // sfix30_En15
  wire signed [29:0] add_signext_50; // sfix30_En15
  wire signed [29:0] add_signext_51; // sfix30_En15
  wire signed [30:0] add_temp_25; // sfix31_En15
  wire signed [29:0] sum27; // sfix30_En15
  wire signed [29:0] add_signext_52; // sfix30_En15
  wire signed [29:0] add_signext_53; // sfix30_En15
  wire signed [30:0] add_temp_26; // sfix31_En15
  wire signed [29:0] sum28; // sfix30_En15
  wire signed [29:0] add_signext_54; // sfix30_En15
  wire signed [29:0] add_signext_55; // sfix30_En15
  wire signed [30:0] add_temp_27; // sfix31_En15
  wire signed [29:0] sum29; // sfix30_En15
  wire signed [29:0] add_signext_56; // sfix30_En15
  wire signed [29:0] add_signext_57; // sfix30_En15
  wire signed [30:0] add_temp_28; // sfix31_En15
  wire signed [29:0] sum30; // sfix30_En15
  wire signed [29:0] add_signext_58; // sfix30_En15
  wire signed [29:0] add_signext_59; // sfix30_En15
  wire signed [30:0] add_temp_29; // sfix31_En15
  wire signed [29:0] sum31; // sfix30_En15
  wire signed [29:0] add_signext_60; // sfix30_En15
  wire signed [29:0] add_signext_61; // sfix30_En15
  wire signed [30:0] add_temp_30; // sfix31_En15
  wire signed [29:0] sum32; // sfix30_En15
  wire signed [29:0] add_signext_62; // sfix30_En15
  wire signed [29:0] add_signext_63; // sfix30_En15
  wire signed [30:0] add_temp_31; // sfix31_En15
  wire signed [29:0] sum33; // sfix30_En15
  wire signed [29:0] add_signext_64; // sfix30_En15
  wire signed [29:0] add_signext_65; // sfix30_En15
  wire signed [30:0] add_temp_32; // sfix31_En15
  wire signed [29:0] sum34; // sfix30_En15
  wire signed [29:0] add_signext_66; // sfix30_En15
  wire signed [29:0] add_signext_67; // sfix30_En15
  wire signed [30:0] add_temp_33; // sfix31_En15
  wire signed [29:0] sum35; // sfix30_En15
  wire signed [29:0] add_signext_68; // sfix30_En15
  wire signed [29:0] add_signext_69; // sfix30_En15
  wire signed [30:0] add_temp_34; // sfix31_En15
  wire signed [29:0] sum36; // sfix30_En15
  wire signed [29:0] add_signext_70; // sfix30_En15
  wire signed [29:0] add_signext_71; // sfix30_En15
  wire signed [30:0] add_temp_35; // sfix31_En15
  wire signed [29:0] sum37; // sfix30_En15
  wire signed [29:0] add_signext_72; // sfix30_En15
  wire signed [29:0] add_signext_73; // sfix30_En15
  wire signed [30:0] add_temp_36; // sfix31_En15
  wire signed [29:0] sum38; // sfix30_En15
  wire signed [29:0] add_signext_74; // sfix30_En15
  wire signed [29:0] add_signext_75; // sfix30_En15
  wire signed [30:0] add_temp_37; // sfix31_En15
  wire signed [29:0] sum39; // sfix30_En15
  wire signed [29:0] add_signext_76; // sfix30_En15
  wire signed [29:0] add_signext_77; // sfix30_En15
  wire signed [30:0] add_temp_38; // sfix31_En15
  wire signed [29:0] sum40; // sfix30_En15
  wire signed [29:0] add_signext_78; // sfix30_En15
  wire signed [29:0] add_signext_79; // sfix30_En15
  wire signed [30:0] add_temp_39; // sfix31_En15
  wire signed [29:0] sum41; // sfix30_En15
  wire signed [29:0] add_signext_80; // sfix30_En15
  wire signed [29:0] add_signext_81; // sfix30_En15
  wire signed [30:0] add_temp_40; // sfix31_En15
  wire signed [29:0] sum42; // sfix30_En15
  wire signed [29:0] add_signext_82; // sfix30_En15
  wire signed [29:0] add_signext_83; // sfix30_En15
  wire signed [30:0] add_temp_41; // sfix31_En15
  wire signed [29:0] sum43; // sfix30_En15
  wire signed [29:0] add_signext_84; // sfix30_En15
  wire signed [29:0] add_signext_85; // sfix30_En15
  wire signed [30:0] add_temp_42; // sfix31_En15
  wire signed [29:0] sum44; // sfix30_En15
  wire signed [29:0] add_signext_86; // sfix30_En15
  wire signed [29:0] add_signext_87; // sfix30_En15
  wire signed [30:0] add_temp_43; // sfix31_En15
  wire signed [29:0] sum45; // sfix30_En15
  wire signed [29:0] add_signext_88; // sfix30_En15
  wire signed [29:0] add_signext_89; // sfix30_En15
  wire signed [30:0] add_temp_44; // sfix31_En15
  wire signed [29:0] sum46; // sfix30_En15
  wire signed [29:0] add_signext_90; // sfix30_En15
  wire signed [29:0] add_signext_91; // sfix30_En15
  wire signed [30:0] add_temp_45; // sfix31_En15
  wire signed [29:0] sum47; // sfix30_En15
  wire signed [29:0] add_signext_92; // sfix30_En15
  wire signed [29:0] add_signext_93; // sfix30_En15
  wire signed [30:0] add_temp_46; // sfix31_En15
  wire signed [29:0] sum48; // sfix30_En15
  wire signed [29:0] add_signext_94; // sfix30_En15
  wire signed [29:0] add_signext_95; // sfix30_En15
  wire signed [30:0] add_temp_47; // sfix31_En15
  wire signed [29:0] sum49; // sfix30_En15
  wire signed [29:0] add_signext_96; // sfix30_En15
  wire signed [29:0] add_signext_97; // sfix30_En15
  wire signed [30:0] add_temp_48; // sfix31_En15
  wire signed [29:0] sum50; // sfix30_En15
  wire signed [29:0] add_signext_98; // sfix30_En15
  wire signed [29:0] add_signext_99; // sfix30_En15
  wire signed [30:0] add_temp_49; // sfix31_En15
  wire signed [29:0] sum51; // sfix30_En15
  wire signed [29:0] add_signext_100; // sfix30_En15
  wire signed [29:0] add_signext_101; // sfix30_En15
  wire signed [30:0] add_temp_50; // sfix31_En15
  wire signed [29:0] sum52; // sfix30_En15
  wire signed [29:0] add_signext_102; // sfix30_En15
  wire signed [29:0] add_signext_103; // sfix30_En15
  wire signed [30:0] add_temp_51; // sfix31_En15
  wire signed [29:0] sum53; // sfix30_En15
  wire signed [29:0] add_signext_104; // sfix30_En15
  wire signed [29:0] add_signext_105; // sfix30_En15
  wire signed [30:0] add_temp_52; // sfix31_En15
  wire signed [29:0] sum54; // sfix30_En15
  wire signed [29:0] add_signext_106; // sfix30_En15
  wire signed [29:0] add_signext_107; // sfix30_En15
  wire signed [30:0] add_temp_53; // sfix31_En15
  wire signed [29:0] sum55; // sfix30_En15
  wire signed [29:0] add_signext_108; // sfix30_En15
  wire signed [29:0] add_signext_109; // sfix30_En15
  wire signed [30:0] add_temp_54; // sfix31_En15
  wire signed [29:0] sum56; // sfix30_En15
  wire signed [29:0] add_signext_110; // sfix30_En15
  wire signed [29:0] add_signext_111; // sfix30_En15
  wire signed [30:0] add_temp_55; // sfix31_En15
  wire signed [29:0] sum57; // sfix30_En15
  wire signed [29:0] add_signext_112; // sfix30_En15
  wire signed [29:0] add_signext_113; // sfix30_En15
  wire signed [30:0] add_temp_56; // sfix31_En15
  wire signed [29:0] sum58; // sfix30_En15
  wire signed [29:0] add_signext_114; // sfix30_En15
  wire signed [29:0] add_signext_115; // sfix30_En15
  wire signed [30:0] add_temp_57; // sfix31_En15
  wire signed [29:0] sum59; // sfix30_En15
  wire signed [29:0] add_signext_116; // sfix30_En15
  wire signed [29:0] add_signext_117; // sfix30_En15
  wire signed [30:0] add_temp_58; // sfix31_En15
  wire signed [29:0] sum60; // sfix30_En15
  wire signed [29:0] add_signext_118; // sfix30_En15
  wire signed [29:0] add_signext_119; // sfix30_En15
  wire signed [30:0] add_temp_59; // sfix31_En15
  wire signed [29:0] sum61; // sfix30_En15
  wire signed [29:0] add_signext_120; // sfix30_En15
  wire signed [29:0] add_signext_121; // sfix30_En15
  wire signed [30:0] add_temp_60; // sfix31_En15
  wire signed [29:0] sum62; // sfix30_En15
  wire signed [29:0] add_signext_122; // sfix30_En15
  wire signed [29:0] add_signext_123; // sfix30_En15
  wire signed [30:0] add_temp_61; // sfix31_En15
  wire signed [29:0] sum63; // sfix30_En15
  wire signed [29:0] add_signext_124; // sfix30_En15
  wire signed [29:0] add_signext_125; // sfix30_En15
  wire signed [30:0] add_temp_62; // sfix31_En15
  wire signed [29:0] sum64; // sfix30_En15
  wire signed [29:0] add_signext_126; // sfix30_En15
  wire signed [29:0] add_signext_127; // sfix30_En15
  wire signed [30:0] add_temp_63; // sfix31_En15
  wire signed [29:0] sum65; // sfix30_En15
  wire signed [29:0] add_signext_128; // sfix30_En15
  wire signed [29:0] add_signext_129; // sfix30_En15
  wire signed [30:0] add_temp_64; // sfix31_En15
  wire signed [29:0] sum66; // sfix30_En15
  wire signed [29:0] add_signext_130; // sfix30_En15
  wire signed [29:0] add_signext_131; // sfix30_En15
  wire signed [30:0] add_temp_65; // sfix31_En15
  wire signed [29:0] sum67; // sfix30_En15
  wire signed [29:0] add_signext_132; // sfix30_En15
  wire signed [29:0] add_signext_133; // sfix30_En15
  wire signed [30:0] add_temp_66; // sfix31_En15
  wire signed [29:0] sum68; // sfix30_En15
  wire signed [29:0] add_signext_134; // sfix30_En15
  wire signed [29:0] add_signext_135; // sfix30_En15
  wire signed [30:0] add_temp_67; // sfix31_En15
  wire signed [29:0] sum69; // sfix30_En15
  wire signed [29:0] add_signext_136; // sfix30_En15
  wire signed [29:0] add_signext_137; // sfix30_En15
  wire signed [30:0] add_temp_68; // sfix31_En15
  wire signed [29:0] sum70; // sfix30_En15
  wire signed [29:0] add_signext_138; // sfix30_En15
  wire signed [29:0] add_signext_139; // sfix30_En15
  wire signed [30:0] add_temp_69; // sfix31_En15
  wire signed [29:0] sum71; // sfix30_En15
  wire signed [29:0] add_signext_140; // sfix30_En15
  wire signed [29:0] add_signext_141; // sfix30_En15
  wire signed [30:0] add_temp_70; // sfix31_En15
  wire signed [29:0] sum72; // sfix30_En15
  wire signed [29:0] add_signext_142; // sfix30_En15
  wire signed [29:0] add_signext_143; // sfix30_En15
  wire signed [30:0] add_temp_71; // sfix31_En15
  wire signed [29:0] sum73; // sfix30_En15
  wire signed [29:0] add_signext_144; // sfix30_En15
  wire signed [29:0] add_signext_145; // sfix30_En15
  wire signed [30:0] add_temp_72; // sfix31_En15
  wire signed [29:0] sum74; // sfix30_En15
  wire signed [29:0] add_signext_146; // sfix30_En15
  wire signed [29:0] add_signext_147; // sfix30_En15
  wire signed [30:0] add_temp_73; // sfix31_En15
  wire signed [29:0] sum75; // sfix30_En15
  wire signed [29:0] add_signext_148; // sfix30_En15
  wire signed [29:0] add_signext_149; // sfix30_En15
  wire signed [30:0] add_temp_74; // sfix31_En15
  wire signed [29:0] sum76; // sfix30_En15
  wire signed [29:0] add_signext_150; // sfix30_En15
  wire signed [29:0] add_signext_151; // sfix30_En15
  wire signed [30:0] add_temp_75; // sfix31_En15
  wire signed [29:0] sum77; // sfix30_En15
  wire signed [29:0] add_signext_152; // sfix30_En15
  wire signed [29:0] add_signext_153; // sfix30_En15
  wire signed [30:0] add_temp_76; // sfix31_En15
  wire signed [29:0] sum78; // sfix30_En15
  wire signed [29:0] add_signext_154; // sfix30_En15
  wire signed [29:0] add_signext_155; // sfix30_En15
  wire signed [30:0] add_temp_77; // sfix31_En15
  wire signed [29:0] sum79; // sfix30_En15
  wire signed [29:0] add_signext_156; // sfix30_En15
  wire signed [29:0] add_signext_157; // sfix30_En15
  wire signed [30:0] add_temp_78; // sfix31_En15
  wire signed [29:0] sum80; // sfix30_En15
  wire signed [29:0] add_signext_158; // sfix30_En15
  wire signed [29:0] add_signext_159; // sfix30_En15
  wire signed [30:0] add_temp_79; // sfix31_En15
  wire signed [29:0] sum81; // sfix30_En15
  wire signed [29:0] add_signext_160; // sfix30_En15
  wire signed [29:0] add_signext_161; // sfix30_En15
  wire signed [30:0] add_temp_80; // sfix31_En15
  wire signed [29:0] sum82; // sfix30_En15
  wire signed [29:0] add_signext_162; // sfix30_En15
  wire signed [29:0] add_signext_163; // sfix30_En15
  wire signed [30:0] add_temp_81; // sfix31_En15
  wire signed [29:0] sum83; // sfix30_En15
  wire signed [29:0] add_signext_164; // sfix30_En15
  wire signed [29:0] add_signext_165; // sfix30_En15
  wire signed [30:0] add_temp_82; // sfix31_En15
  wire signed [29:0] sum84; // sfix30_En15
  wire signed [29:0] add_signext_166; // sfix30_En15
  wire signed [29:0] add_signext_167; // sfix30_En15
  wire signed [30:0] add_temp_83; // sfix31_En15
  wire signed [29:0] sum85; // sfix30_En15
  wire signed [29:0] add_signext_168; // sfix30_En15
  wire signed [29:0] add_signext_169; // sfix30_En15
  wire signed [30:0] add_temp_84; // sfix31_En15
  wire signed [29:0] sum86; // sfix30_En15
  wire signed [29:0] add_signext_170; // sfix30_En15
  wire signed [29:0] add_signext_171; // sfix30_En15
  wire signed [30:0] add_temp_85; // sfix31_En15
  wire signed [29:0] sum87; // sfix30_En15
  wire signed [29:0] add_signext_172; // sfix30_En15
  wire signed [29:0] add_signext_173; // sfix30_En15
  wire signed [30:0] add_temp_86; // sfix31_En15
  wire signed [29:0] sum88; // sfix30_En15
  wire signed [29:0] add_signext_174; // sfix30_En15
  wire signed [29:0] add_signext_175; // sfix30_En15
  wire signed [30:0] add_temp_87; // sfix31_En15
  wire signed [29:0] sum89; // sfix30_En15
  wire signed [29:0] add_signext_176; // sfix30_En15
  wire signed [29:0] add_signext_177; // sfix30_En15
  wire signed [30:0] add_temp_88; // sfix31_En15
  wire signed [29:0] sum90; // sfix30_En15
  wire signed [29:0] add_signext_178; // sfix30_En15
  wire signed [29:0] add_signext_179; // sfix30_En15
  wire signed [30:0] add_temp_89; // sfix31_En15
  wire signed [29:0] sum91; // sfix30_En15
  wire signed [29:0] add_signext_180; // sfix30_En15
  wire signed [29:0] add_signext_181; // sfix30_En15
  wire signed [30:0] add_temp_90; // sfix31_En15
  wire signed [29:0] sum92; // sfix30_En15
  wire signed [29:0] add_signext_182; // sfix30_En15
  wire signed [29:0] add_signext_183; // sfix30_En15
  wire signed [30:0] add_temp_91; // sfix31_En15
  wire signed [29:0] sum93; // sfix30_En15
  wire signed [29:0] add_signext_184; // sfix30_En15
  wire signed [29:0] add_signext_185; // sfix30_En15
  wire signed [30:0] add_temp_92; // sfix31_En15
  wire signed [29:0] sum94; // sfix30_En15
  wire signed [29:0] add_signext_186; // sfix30_En15
  wire signed [29:0] add_signext_187; // sfix30_En15
  wire signed [30:0] add_temp_93; // sfix31_En15
  wire signed [29:0] sum95; // sfix30_En15
  wire signed [29:0] add_signext_188; // sfix30_En15
  wire signed [29:0] add_signext_189; // sfix30_En15
  wire signed [30:0] add_temp_94; // sfix31_En15
  wire signed [29:0] sum96; // sfix30_En15
  wire signed [29:0] add_signext_190; // sfix30_En15
  wire signed [29:0] add_signext_191; // sfix30_En15
  wire signed [30:0] add_temp_95; // sfix31_En15
  wire signed [29:0] sum97; // sfix30_En15
  wire signed [29:0] add_signext_192; // sfix30_En15
  wire signed [29:0] add_signext_193; // sfix30_En15
  wire signed [30:0] add_temp_96; // sfix31_En15
  wire signed [29:0] sum98; // sfix30_En15
  wire signed [29:0] add_signext_194; // sfix30_En15
  wire signed [29:0] add_signext_195; // sfix30_En15
  wire signed [30:0] add_temp_97; // sfix31_En15
  reg  signed [29:0] output_register; // sfix30_En15

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
        delay_pipeline[52] <= 0;
        delay_pipeline[53] <= 0;
        delay_pipeline[54] <= 0;
        delay_pipeline[55] <= 0;
        delay_pipeline[56] <= 0;
        delay_pipeline[57] <= 0;
        delay_pipeline[58] <= 0;
        delay_pipeline[59] <= 0;
        delay_pipeline[60] <= 0;
        delay_pipeline[61] <= 0;
        delay_pipeline[62] <= 0;
        delay_pipeline[63] <= 0;
        delay_pipeline[64] <= 0;
        delay_pipeline[65] <= 0;
        delay_pipeline[66] <= 0;
        delay_pipeline[67] <= 0;
        delay_pipeline[68] <= 0;
        delay_pipeline[69] <= 0;
        delay_pipeline[70] <= 0;
        delay_pipeline[71] <= 0;
        delay_pipeline[72] <= 0;
        delay_pipeline[73] <= 0;
        delay_pipeline[74] <= 0;
        delay_pipeline[75] <= 0;
        delay_pipeline[76] <= 0;
        delay_pipeline[77] <= 0;
        delay_pipeline[78] <= 0;
        delay_pipeline[79] <= 0;
        delay_pipeline[80] <= 0;
        delay_pipeline[81] <= 0;
        delay_pipeline[82] <= 0;
        delay_pipeline[83] <= 0;
        delay_pipeline[84] <= 0;
        delay_pipeline[85] <= 0;
        delay_pipeline[86] <= 0;
        delay_pipeline[87] <= 0;
        delay_pipeline[88] <= 0;
        delay_pipeline[89] <= 0;
        delay_pipeline[90] <= 0;
        delay_pipeline[91] <= 0;
        delay_pipeline[92] <= 0;
        delay_pipeline[93] <= 0;
        delay_pipeline[94] <= 0;
        delay_pipeline[95] <= 0;
        delay_pipeline[96] <= 0;
        delay_pipeline[97] <= 0;
        delay_pipeline[98] <= 0;
        delay_pipeline[99] <= 0;
        delay_pipeline[100] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
          delay_pipeline[52] <= delay_pipeline[51];
          delay_pipeline[53] <= delay_pipeline[52];
          delay_pipeline[54] <= delay_pipeline[53];
          delay_pipeline[55] <= delay_pipeline[54];
          delay_pipeline[56] <= delay_pipeline[55];
          delay_pipeline[57] <= delay_pipeline[56];
          delay_pipeline[58] <= delay_pipeline[57];
          delay_pipeline[59] <= delay_pipeline[58];
          delay_pipeline[60] <= delay_pipeline[59];
          delay_pipeline[61] <= delay_pipeline[60];
          delay_pipeline[62] <= delay_pipeline[61];
          delay_pipeline[63] <= delay_pipeline[62];
          delay_pipeline[64] <= delay_pipeline[63];
          delay_pipeline[65] <= delay_pipeline[64];
          delay_pipeline[66] <= delay_pipeline[65];
          delay_pipeline[67] <= delay_pipeline[66];
          delay_pipeline[68] <= delay_pipeline[67];
          delay_pipeline[69] <= delay_pipeline[68];
          delay_pipeline[70] <= delay_pipeline[69];
          delay_pipeline[71] <= delay_pipeline[70];
          delay_pipeline[72] <= delay_pipeline[71];
          delay_pipeline[73] <= delay_pipeline[72];
          delay_pipeline[74] <= delay_pipeline[73];
          delay_pipeline[75] <= delay_pipeline[74];
          delay_pipeline[76] <= delay_pipeline[75];
          delay_pipeline[77] <= delay_pipeline[76];
          delay_pipeline[78] <= delay_pipeline[77];
          delay_pipeline[79] <= delay_pipeline[78];
          delay_pipeline[80] <= delay_pipeline[79];
          delay_pipeline[81] <= delay_pipeline[80];
          delay_pipeline[82] <= delay_pipeline[81];
          delay_pipeline[83] <= delay_pipeline[82];
          delay_pipeline[84] <= delay_pipeline[83];
          delay_pipeline[85] <= delay_pipeline[84];
          delay_pipeline[86] <= delay_pipeline[85];
          delay_pipeline[87] <= delay_pipeline[86];
          delay_pipeline[88] <= delay_pipeline[87];
          delay_pipeline[89] <= delay_pipeline[88];
          delay_pipeline[90] <= delay_pipeline[89];
          delay_pipeline[91] <= delay_pipeline[90];
          delay_pipeline[92] <= delay_pipeline[91];
          delay_pipeline[93] <= delay_pipeline[92];
          delay_pipeline[94] <= delay_pipeline[93];
          delay_pipeline[95] <= delay_pipeline[94];
          delay_pipeline[96] <= delay_pipeline[95];
          delay_pipeline[97] <= delay_pipeline[96];
          delay_pipeline[98] <= delay_pipeline[97];
          delay_pipeline[99] <= delay_pipeline[98];
          delay_pipeline[100] <= delay_pipeline[99];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[99] * coeff100;
  assign product100 = mul_temp[26:0];

  assign product99 = $signed({delay_pipeline[98][13:0], 4'b0000});

  assign mul_temp_1 = delay_pipeline[97] * coeff98;
  assign product98 = mul_temp_1[26:0];

  assign mul_temp_2 = delay_pipeline[96] * coeff97;
  assign product97 = mul_temp_2[26:0];

  assign mul_temp_3 = delay_pipeline[95] * coeff96;
  assign product96 = mul_temp_3[26:0];

  assign mul_temp_4 = delay_pipeline[94] * coeff95;
  assign product95 = mul_temp_4[26:0];

  assign mul_temp_5 = delay_pipeline[93] * coeff94;
  assign product94 = mul_temp_5[26:0];

  assign mul_temp_6 = delay_pipeline[92] * coeff93;
  assign product93 = mul_temp_6[26:0];

  assign mul_temp_7 = delay_pipeline[91] * coeff92;
  assign product92 = mul_temp_7[26:0];

  assign mul_temp_8 = delay_pipeline[90] * coeff91;
  assign product91 = mul_temp_8[26:0];

  assign mul_temp_9 = delay_pipeline[89] * coeff90;
  assign product90 = mul_temp_9[26:0];

  assign mul_temp_10 = delay_pipeline[88] * coeff89;
  assign product89 = mul_temp_10[26:0];

  assign mul_temp_11 = delay_pipeline[87] * coeff88;
  assign product88 = mul_temp_11[26:0];

  assign mul_temp_12 = delay_pipeline[86] * coeff87;
  assign product87 = mul_temp_12[26:0];

  assign mul_temp_13 = delay_pipeline[85] * coeff86;
  assign product86 = mul_temp_13[26:0];

  assign mul_temp_14 = delay_pipeline[84] * coeff85;
  assign product85 = mul_temp_14[26:0];

  assign mul_temp_15 = delay_pipeline[83] * coeff84;
  assign product84 = mul_temp_15[26:0];

  assign mul_temp_16 = delay_pipeline[82] * coeff83;
  assign product83 = mul_temp_16[26:0];

  assign mul_temp_17 = delay_pipeline[81] * coeff82;
  assign product82 = mul_temp_17[26:0];

  assign mul_temp_18 = delay_pipeline[80] * coeff81;
  assign product81 = mul_temp_18[26:0];

  assign mul_temp_19 = delay_pipeline[79] * coeff80;
  assign product80 = mul_temp_19[26:0];

  assign mul_temp_20 = delay_pipeline[78] * coeff79;
  assign product79 = mul_temp_20[26:0];

  assign mul_temp_21 = delay_pipeline[77] * coeff78;
  assign product78 = mul_temp_21[26:0];

  assign mul_temp_22 = delay_pipeline[76] * coeff77;
  assign product77 = mul_temp_22[26:0];

  assign mul_temp_23 = delay_pipeline[75] * coeff76;
  assign product76 = mul_temp_23[26:0];

  assign mul_temp_24 = delay_pipeline[74] * coeff75;
  assign product75 = mul_temp_24[26:0];

  assign mul_temp_25 = delay_pipeline[73] * coeff74;
  assign product74 = mul_temp_25[26:0];

  assign mul_temp_26 = delay_pipeline[72] * coeff73;
  assign product73 = mul_temp_26[26:0];

  assign mul_temp_27 = delay_pipeline[71] * coeff72;
  assign product72 = mul_temp_27[26:0];

  assign mul_temp_28 = delay_pipeline[70] * coeff71;
  assign product71 = mul_temp_28[26:0];

  assign mul_temp_29 = delay_pipeline[69] * coeff70;
  assign product70 = mul_temp_29[26:0];

  assign mul_temp_30 = delay_pipeline[68] * coeff69;
  assign product69 = mul_temp_30[26:0];

  assign mul_temp_31 = delay_pipeline[67] * coeff68;
  assign product68 = mul_temp_31[26:0];

  assign mul_temp_32 = delay_pipeline[66] * coeff67;
  assign product67 = mul_temp_32[26:0];

  assign mul_temp_33 = delay_pipeline[65] * coeff66;
  assign product66 = mul_temp_33[26:0];

  assign mul_temp_34 = delay_pipeline[64] * coeff65;
  assign product65 = mul_temp_34[26:0];

  assign mul_temp_35 = delay_pipeline[63] * coeff64;
  assign product64 = mul_temp_35[26:0];

  assign mul_temp_36 = delay_pipeline[62] * coeff63;
  assign product63 = mul_temp_36[26:0];

  assign mul_temp_37 = delay_pipeline[61] * coeff62;
  assign product62 = mul_temp_37[26:0];

  assign mul_temp_38 = delay_pipeline[60] * coeff61;
  assign product61 = mul_temp_38[26:0];

  assign mul_temp_39 = delay_pipeline[59] * coeff60;
  assign product60 = mul_temp_39[26:0];

  assign mul_temp_40 = delay_pipeline[58] * coeff59;
  assign product59 = mul_temp_40[26:0];

  assign mul_temp_41 = delay_pipeline[57] * coeff58;
  assign product58 = mul_temp_41[26:0];

  assign mul_temp_42 = delay_pipeline[56] * coeff57;
  assign product57 = mul_temp_42[26:0];

  assign mul_temp_43 = delay_pipeline[55] * coeff56;
  assign product56 = mul_temp_43[26:0];

  assign mul_temp_44 = delay_pipeline[54] * coeff55;
  assign product55 = mul_temp_44[26:0];

  assign mul_temp_45 = delay_pipeline[53] * coeff54;
  assign product54 = mul_temp_45[26:0];

  assign mul_temp_46 = delay_pipeline[52] * coeff53;
  assign product53 = mul_temp_46[26:0];

  assign mul_temp_47 = delay_pipeline[51] * coeff52;
  assign product52 = mul_temp_47[26:0];

  assign mul_temp_48 = delay_pipeline[50] * coeff51;
  assign product51 = mul_temp_48[26:0];

  assign mul_temp_49 = delay_pipeline[49] * coeff50;
  assign product50 = mul_temp_49[26:0];

  assign mul_temp_50 = delay_pipeline[48] * coeff49;
  assign product49 = mul_temp_50[26:0];

  assign mul_temp_51 = delay_pipeline[47] * coeff48;
  assign product48 = mul_temp_51[26:0];

  assign mul_temp_52 = delay_pipeline[46] * coeff47;
  assign product47 = mul_temp_52[26:0];

  assign mul_temp_53 = delay_pipeline[45] * coeff46;
  assign product46 = mul_temp_53[26:0];

  assign mul_temp_54 = delay_pipeline[44] * coeff45;
  assign product45 = mul_temp_54[26:0];

  assign mul_temp_55 = delay_pipeline[43] * coeff44;
  assign product44 = mul_temp_55[26:0];

  assign mul_temp_56 = delay_pipeline[42] * coeff43;
  assign product43 = mul_temp_56[26:0];

  assign mul_temp_57 = delay_pipeline[41] * coeff42;
  assign product42 = mul_temp_57[26:0];

  assign mul_temp_58 = delay_pipeline[40] * coeff41;
  assign product41 = mul_temp_58[26:0];

  assign mul_temp_59 = delay_pipeline[39] * coeff40;
  assign product40 = mul_temp_59[26:0];

  assign mul_temp_60 = delay_pipeline[38] * coeff39;
  assign product39 = mul_temp_60[26:0];

  assign mul_temp_61 = delay_pipeline[37] * coeff38;
  assign product38 = mul_temp_61[26:0];

  assign mul_temp_62 = delay_pipeline[36] * coeff37;
  assign product37 = mul_temp_62[26:0];

  assign mul_temp_63 = delay_pipeline[35] * coeff36;
  assign product36 = mul_temp_63[26:0];

  assign mul_temp_64 = delay_pipeline[34] * coeff35;
  assign product35 = mul_temp_64[26:0];

  assign mul_temp_65 = delay_pipeline[33] * coeff34;
  assign product34 = mul_temp_65[26:0];

  assign mul_temp_66 = delay_pipeline[32] * coeff33;
  assign product33 = mul_temp_66[26:0];

  assign mul_temp_67 = delay_pipeline[31] * coeff32;
  assign product32 = mul_temp_67[26:0];

  assign mul_temp_68 = delay_pipeline[30] * coeff31;
  assign product31 = mul_temp_68[26:0];

  assign mul_temp_69 = delay_pipeline[29] * coeff30;
  assign product30 = mul_temp_69[26:0];

  assign mul_temp_70 = delay_pipeline[28] * coeff29;
  assign product29 = mul_temp_70[26:0];

  assign mul_temp_71 = delay_pipeline[27] * coeff28;
  assign product28 = mul_temp_71[26:0];

  assign mul_temp_72 = delay_pipeline[26] * coeff27;
  assign product27 = mul_temp_72[26:0];

  assign mul_temp_73 = delay_pipeline[25] * coeff26;
  assign product26 = mul_temp_73[26:0];

  assign mul_temp_74 = delay_pipeline[24] * coeff25;
  assign product25 = mul_temp_74[26:0];

  assign mul_temp_75 = delay_pipeline[23] * coeff24;
  assign product24 = mul_temp_75[26:0];

  assign mul_temp_76 = delay_pipeline[22] * coeff23;
  assign product23 = mul_temp_76[26:0];

  assign mul_temp_77 = delay_pipeline[21] * coeff22;
  assign product22 = mul_temp_77[26:0];

  assign mul_temp_78 = delay_pipeline[20] * coeff21;
  assign product21 = mul_temp_78[26:0];

  assign mul_temp_79 = delay_pipeline[19] * coeff20;
  assign product20 = mul_temp_79[26:0];

  assign mul_temp_80 = delay_pipeline[18] * coeff19;
  assign product19 = mul_temp_80[26:0];

  assign mul_temp_81 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_81[26:0];

  assign mul_temp_82 = delay_pipeline[16] * coeff17;
  assign product17 = mul_temp_82[26:0];

  assign mul_temp_83 = delay_pipeline[15] * coeff16;
  assign product16 = mul_temp_83[26:0];

  assign mul_temp_84 = delay_pipeline[14] * coeff15;
  assign product15 = mul_temp_84[26:0];

  assign mul_temp_85 = delay_pipeline[13] * coeff14;
  assign product14 = mul_temp_85[26:0];

  assign mul_temp_86 = delay_pipeline[12] * coeff13;
  assign product13 = mul_temp_86[26:0];

  assign mul_temp_87 = delay_pipeline[11] * coeff12;
  assign product12 = mul_temp_87[26:0];

  assign mul_temp_88 = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp_88[26:0];

  assign mul_temp_89 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_89[26:0];

  assign mul_temp_90 = delay_pipeline[8] * coeff9;
  assign product9 = mul_temp_90[26:0];

  assign mul_temp_91 = delay_pipeline[7] * coeff8;
  assign product8 = mul_temp_91[26:0];

  assign mul_temp_92 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_92[26:0];

  assign mul_temp_93 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_93[26:0];

  assign mul_temp_94 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_94[26:0];

  assign mul_temp_95 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_95[26:0];

  assign product3 = $signed({delay_pipeline[2][13:0], 4'b0000});

  assign mul_temp_96 = delay_pipeline[1] * coeff2;
  assign product2 = mul_temp_96[26:0];

  assign add_signext = product2;
  assign add_signext_1 = product3;
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = $signed({{2{add_temp[27]}}, add_temp});

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{3{product4[26]}}, product4});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[29:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{3{product5[26]}}, product5});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[29:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{3{product6[26]}}, product6});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[29:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{3{product7[26]}}, product7});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[29:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{3{product8[26]}}, product8});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[29:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{3{product9[26]}}, product9});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[29:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{3{product10[26]}}, product10});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[29:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{3{product11[26]}}, product11});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[29:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{3{product12[26]}}, product12});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[29:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{3{product13[26]}}, product13});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[29:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{3{product14[26]}}, product14});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[29:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{3{product15[26]}}, product15});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[29:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{3{product16[26]}}, product16});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[29:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{3{product17[26]}}, product17});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[29:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{3{product18[26]}}, product18});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[29:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{3{product19[26]}}, product19});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[29:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{3{product20[26]}}, product20});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[29:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{3{product21[26]}}, product21});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[29:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{3{product22[26]}}, product22});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[29:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{3{product23[26]}}, product23});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[29:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{3{product24[26]}}, product24});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[29:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{3{product25[26]}}, product25});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[29:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{3{product26[26]}}, product26});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[29:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{3{product27[26]}}, product27});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[29:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{3{product28[26]}}, product28});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[29:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{3{product29[26]}}, product29});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[29:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{3{product30[26]}}, product30});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[29:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{3{product31[26]}}, product31});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[29:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{3{product32[26]}}, product32});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[29:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{3{product33[26]}}, product33});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[29:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{3{product34[26]}}, product34});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[29:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = $signed({{3{product35[26]}}, product35});
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = add_temp_32[29:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = $signed({{3{product36[26]}}, product36});
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = add_temp_33[29:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = $signed({{3{product37[26]}}, product37});
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = add_temp_34[29:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = $signed({{3{product38[26]}}, product38});
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = add_temp_35[29:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = $signed({{3{product39[26]}}, product39});
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = add_temp_36[29:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = $signed({{3{product40[26]}}, product40});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = add_temp_37[29:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = $signed({{3{product41[26]}}, product41});
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = add_temp_38[29:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = $signed({{3{product42[26]}}, product42});
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = add_temp_39[29:0];

  assign add_signext_80 = sum40;
  assign add_signext_81 = $signed({{3{product43[26]}}, product43});
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum41 = add_temp_40[29:0];

  assign add_signext_82 = sum41;
  assign add_signext_83 = $signed({{3{product44[26]}}, product44});
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum42 = add_temp_41[29:0];

  assign add_signext_84 = sum42;
  assign add_signext_85 = $signed({{3{product45[26]}}, product45});
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum43 = add_temp_42[29:0];

  assign add_signext_86 = sum43;
  assign add_signext_87 = $signed({{3{product46[26]}}, product46});
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum44 = add_temp_43[29:0];

  assign add_signext_88 = sum44;
  assign add_signext_89 = $signed({{3{product47[26]}}, product47});
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum45 = add_temp_44[29:0];

  assign add_signext_90 = sum45;
  assign add_signext_91 = $signed({{3{product48[26]}}, product48});
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum46 = add_temp_45[29:0];

  assign add_signext_92 = sum46;
  assign add_signext_93 = $signed({{3{product49[26]}}, product49});
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum47 = add_temp_46[29:0];

  assign add_signext_94 = sum47;
  assign add_signext_95 = $signed({{3{product50[26]}}, product50});
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum48 = add_temp_47[29:0];

  assign add_signext_96 = sum48;
  assign add_signext_97 = $signed({{3{product51[26]}}, product51});
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum49 = add_temp_48[29:0];

  assign add_signext_98 = sum49;
  assign add_signext_99 = $signed({{3{product52[26]}}, product52});
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum50 = add_temp_49[29:0];

  assign add_signext_100 = sum50;
  assign add_signext_101 = $signed({{3{product53[26]}}, product53});
  assign add_temp_50 = add_signext_100 + add_signext_101;
  assign sum51 = add_temp_50[29:0];

  assign add_signext_102 = sum51;
  assign add_signext_103 = $signed({{3{product54[26]}}, product54});
  assign add_temp_51 = add_signext_102 + add_signext_103;
  assign sum52 = add_temp_51[29:0];

  assign add_signext_104 = sum52;
  assign add_signext_105 = $signed({{3{product55[26]}}, product55});
  assign add_temp_52 = add_signext_104 + add_signext_105;
  assign sum53 = add_temp_52[29:0];

  assign add_signext_106 = sum53;
  assign add_signext_107 = $signed({{3{product56[26]}}, product56});
  assign add_temp_53 = add_signext_106 + add_signext_107;
  assign sum54 = add_temp_53[29:0];

  assign add_signext_108 = sum54;
  assign add_signext_109 = $signed({{3{product57[26]}}, product57});
  assign add_temp_54 = add_signext_108 + add_signext_109;
  assign sum55 = add_temp_54[29:0];

  assign add_signext_110 = sum55;
  assign add_signext_111 = $signed({{3{product58[26]}}, product58});
  assign add_temp_55 = add_signext_110 + add_signext_111;
  assign sum56 = add_temp_55[29:0];

  assign add_signext_112 = sum56;
  assign add_signext_113 = $signed({{3{product59[26]}}, product59});
  assign add_temp_56 = add_signext_112 + add_signext_113;
  assign sum57 = add_temp_56[29:0];

  assign add_signext_114 = sum57;
  assign add_signext_115 = $signed({{3{product60[26]}}, product60});
  assign add_temp_57 = add_signext_114 + add_signext_115;
  assign sum58 = add_temp_57[29:0];

  assign add_signext_116 = sum58;
  assign add_signext_117 = $signed({{3{product61[26]}}, product61});
  assign add_temp_58 = add_signext_116 + add_signext_117;
  assign sum59 = add_temp_58[29:0];

  assign add_signext_118 = sum59;
  assign add_signext_119 = $signed({{3{product62[26]}}, product62});
  assign add_temp_59 = add_signext_118 + add_signext_119;
  assign sum60 = add_temp_59[29:0];

  assign add_signext_120 = sum60;
  assign add_signext_121 = $signed({{3{product63[26]}}, product63});
  assign add_temp_60 = add_signext_120 + add_signext_121;
  assign sum61 = add_temp_60[29:0];

  assign add_signext_122 = sum61;
  assign add_signext_123 = $signed({{3{product64[26]}}, product64});
  assign add_temp_61 = add_signext_122 + add_signext_123;
  assign sum62 = add_temp_61[29:0];

  assign add_signext_124 = sum62;
  assign add_signext_125 = $signed({{3{product65[26]}}, product65});
  assign add_temp_62 = add_signext_124 + add_signext_125;
  assign sum63 = add_temp_62[29:0];

  assign add_signext_126 = sum63;
  assign add_signext_127 = $signed({{3{product66[26]}}, product66});
  assign add_temp_63 = add_signext_126 + add_signext_127;
  assign sum64 = add_temp_63[29:0];

  assign add_signext_128 = sum64;
  assign add_signext_129 = $signed({{3{product67[26]}}, product67});
  assign add_temp_64 = add_signext_128 + add_signext_129;
  assign sum65 = add_temp_64[29:0];

  assign add_signext_130 = sum65;
  assign add_signext_131 = $signed({{3{product68[26]}}, product68});
  assign add_temp_65 = add_signext_130 + add_signext_131;
  assign sum66 = add_temp_65[29:0];

  assign add_signext_132 = sum66;
  assign add_signext_133 = $signed({{3{product69[26]}}, product69});
  assign add_temp_66 = add_signext_132 + add_signext_133;
  assign sum67 = add_temp_66[29:0];

  assign add_signext_134 = sum67;
  assign add_signext_135 = $signed({{3{product70[26]}}, product70});
  assign add_temp_67 = add_signext_134 + add_signext_135;
  assign sum68 = add_temp_67[29:0];

  assign add_signext_136 = sum68;
  assign add_signext_137 = $signed({{3{product71[26]}}, product71});
  assign add_temp_68 = add_signext_136 + add_signext_137;
  assign sum69 = add_temp_68[29:0];

  assign add_signext_138 = sum69;
  assign add_signext_139 = $signed({{3{product72[26]}}, product72});
  assign add_temp_69 = add_signext_138 + add_signext_139;
  assign sum70 = add_temp_69[29:0];

  assign add_signext_140 = sum70;
  assign add_signext_141 = $signed({{3{product73[26]}}, product73});
  assign add_temp_70 = add_signext_140 + add_signext_141;
  assign sum71 = add_temp_70[29:0];

  assign add_signext_142 = sum71;
  assign add_signext_143 = $signed({{3{product74[26]}}, product74});
  assign add_temp_71 = add_signext_142 + add_signext_143;
  assign sum72 = add_temp_71[29:0];

  assign add_signext_144 = sum72;
  assign add_signext_145 = $signed({{3{product75[26]}}, product75});
  assign add_temp_72 = add_signext_144 + add_signext_145;
  assign sum73 = add_temp_72[29:0];

  assign add_signext_146 = sum73;
  assign add_signext_147 = $signed({{3{product76[26]}}, product76});
  assign add_temp_73 = add_signext_146 + add_signext_147;
  assign sum74 = add_temp_73[29:0];

  assign add_signext_148 = sum74;
  assign add_signext_149 = $signed({{3{product77[26]}}, product77});
  assign add_temp_74 = add_signext_148 + add_signext_149;
  assign sum75 = add_temp_74[29:0];

  assign add_signext_150 = sum75;
  assign add_signext_151 = $signed({{3{product78[26]}}, product78});
  assign add_temp_75 = add_signext_150 + add_signext_151;
  assign sum76 = add_temp_75[29:0];

  assign add_signext_152 = sum76;
  assign add_signext_153 = $signed({{3{product79[26]}}, product79});
  assign add_temp_76 = add_signext_152 + add_signext_153;
  assign sum77 = add_temp_76[29:0];

  assign add_signext_154 = sum77;
  assign add_signext_155 = $signed({{3{product80[26]}}, product80});
  assign add_temp_77 = add_signext_154 + add_signext_155;
  assign sum78 = add_temp_77[29:0];

  assign add_signext_156 = sum78;
  assign add_signext_157 = $signed({{3{product81[26]}}, product81});
  assign add_temp_78 = add_signext_156 + add_signext_157;
  assign sum79 = add_temp_78[29:0];

  assign add_signext_158 = sum79;
  assign add_signext_159 = $signed({{3{product82[26]}}, product82});
  assign add_temp_79 = add_signext_158 + add_signext_159;
  assign sum80 = add_temp_79[29:0];

  assign add_signext_160 = sum80;
  assign add_signext_161 = $signed({{3{product83[26]}}, product83});
  assign add_temp_80 = add_signext_160 + add_signext_161;
  assign sum81 = add_temp_80[29:0];

  assign add_signext_162 = sum81;
  assign add_signext_163 = $signed({{3{product84[26]}}, product84});
  assign add_temp_81 = add_signext_162 + add_signext_163;
  assign sum82 = add_temp_81[29:0];

  assign add_signext_164 = sum82;
  assign add_signext_165 = $signed({{3{product85[26]}}, product85});
  assign add_temp_82 = add_signext_164 + add_signext_165;
  assign sum83 = add_temp_82[29:0];

  assign add_signext_166 = sum83;
  assign add_signext_167 = $signed({{3{product86[26]}}, product86});
  assign add_temp_83 = add_signext_166 + add_signext_167;
  assign sum84 = add_temp_83[29:0];

  assign add_signext_168 = sum84;
  assign add_signext_169 = $signed({{3{product87[26]}}, product87});
  assign add_temp_84 = add_signext_168 + add_signext_169;
  assign sum85 = add_temp_84[29:0];

  assign add_signext_170 = sum85;
  assign add_signext_171 = $signed({{3{product88[26]}}, product88});
  assign add_temp_85 = add_signext_170 + add_signext_171;
  assign sum86 = add_temp_85[29:0];

  assign add_signext_172 = sum86;
  assign add_signext_173 = $signed({{3{product89[26]}}, product89});
  assign add_temp_86 = add_signext_172 + add_signext_173;
  assign sum87 = add_temp_86[29:0];

  assign add_signext_174 = sum87;
  assign add_signext_175 = $signed({{3{product90[26]}}, product90});
  assign add_temp_87 = add_signext_174 + add_signext_175;
  assign sum88 = add_temp_87[29:0];

  assign add_signext_176 = sum88;
  assign add_signext_177 = $signed({{3{product91[26]}}, product91});
  assign add_temp_88 = add_signext_176 + add_signext_177;
  assign sum89 = add_temp_88[29:0];

  assign add_signext_178 = sum89;
  assign add_signext_179 = $signed({{3{product92[26]}}, product92});
  assign add_temp_89 = add_signext_178 + add_signext_179;
  assign sum90 = add_temp_89[29:0];

  assign add_signext_180 = sum90;
  assign add_signext_181 = $signed({{3{product93[26]}}, product93});
  assign add_temp_90 = add_signext_180 + add_signext_181;
  assign sum91 = add_temp_90[29:0];

  assign add_signext_182 = sum91;
  assign add_signext_183 = $signed({{3{product94[26]}}, product94});
  assign add_temp_91 = add_signext_182 + add_signext_183;
  assign sum92 = add_temp_91[29:0];

  assign add_signext_184 = sum92;
  assign add_signext_185 = $signed({{3{product95[26]}}, product95});
  assign add_temp_92 = add_signext_184 + add_signext_185;
  assign sum93 = add_temp_92[29:0];

  assign add_signext_186 = sum93;
  assign add_signext_187 = $signed({{3{product96[26]}}, product96});
  assign add_temp_93 = add_signext_186 + add_signext_187;
  assign sum94 = add_temp_93[29:0];

  assign add_signext_188 = sum94;
  assign add_signext_189 = $signed({{3{product97[26]}}, product97});
  assign add_temp_94 = add_signext_188 + add_signext_189;
  assign sum95 = add_temp_94[29:0];

  assign add_signext_190 = sum95;
  assign add_signext_191 = $signed({{3{product98[26]}}, product98});
  assign add_temp_95 = add_signext_190 + add_signext_191;
  assign sum96 = add_temp_95[29:0];

  assign add_signext_192 = sum96;
  assign add_signext_193 = $signed({{3{product99[26]}}, product99});
  assign add_temp_96 = add_signext_192 + add_signext_193;
  assign sum97 = add_temp_96[29:0];

  assign add_signext_194 = sum97;
  assign add_signext_195 = $signed({{3{product100[26]}}, product100});
  assign add_temp_97 = add_signext_194 + add_signext_195;
  assign sum98 = add_temp_97[29:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum98;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // Lowpass_5_MHz_V2
